// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Assumptions
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assumptionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Assumptions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Service_Nature("Service_Nature"),
		Properties("Properties"),
		Percentage("Percentage"),
		Effort_Orchestation("Effort_Orchestation"),
		Assumptions_Template("MyFirstModule.Assumptions_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Assumptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Assumptions"));
	}

	protected Assumptions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assumptionsMendixObject)
	{
		if (assumptionsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Assumptions", assumptionsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Assumptions");

		this.assumptionsMendixObject = assumptionsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Assumptions.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Assumptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Assumptions.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Assumptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Assumptions(context, mendixObject);
	}

	public static myfirstmodule.proxies.Assumptions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Assumptions.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Assumptions> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Assumptions> result = new java.util.ArrayList<myfirstmodule.proxies.Assumptions>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Assumptions" + xpathConstraint))
			result.add(myfirstmodule.proxies.Assumptions.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Service_Nature
	 */
	public final java.lang.String getService_Nature()
	{
		return getService_Nature(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Nature
	 */
	public final java.lang.String getService_Nature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Nature.toString());
	}

	/**
	 * Set value of Service_Nature
	 * @param service_nature
	 */
	public final void setService_Nature(java.lang.String service_nature)
	{
		setService_Nature(getContext(), service_nature);
	}

	/**
	 * Set value of Service_Nature
	 * @param context
	 * @param service_nature
	 */
	public final void setService_Nature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_nature)
	{
		getMendixObject().setValue(context, MemberNames.Service_Nature.toString(), service_nature);
	}

	/**
	 * @return value of Properties
	 */
	public final java.lang.String getProperties()
	{
		return getProperties(getContext());
	}

	/**
	 * @param context
	 * @return value of Properties
	 */
	public final java.lang.String getProperties(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Properties.toString());
	}

	/**
	 * Set value of Properties
	 * @param properties
	 */
	public final void setProperties(java.lang.String properties)
	{
		setProperties(getContext(), properties);
	}

	/**
	 * Set value of Properties
	 * @param context
	 * @param properties
	 */
	public final void setProperties(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String properties)
	{
		getMendixObject().setValue(context, MemberNames.Properties.toString(), properties);
	}

	/**
	 * @return value of Percentage
	 */
	public final java.math.BigDecimal getPercentage()
	{
		return getPercentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Percentage
	 */
	public final java.math.BigDecimal getPercentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Percentage.toString());
	}

	/**
	 * Set value of Percentage
	 * @param percentage
	 */
	public final void setPercentage(java.math.BigDecimal percentage)
	{
		setPercentage(getContext(), percentage);
	}

	/**
	 * Set value of Percentage
	 * @param context
	 * @param percentage
	 */
	public final void setPercentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal percentage)
	{
		getMendixObject().setValue(context, MemberNames.Percentage.toString(), percentage);
	}

	/**
	 * @return value of Effort_Orchestation
	 */
	public final java.math.BigDecimal getEffort_Orchestation()
	{
		return getEffort_Orchestation(getContext());
	}

	/**
	 * @param context
	 * @return value of Effort_Orchestation
	 */
	public final java.math.BigDecimal getEffort_Orchestation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Effort_Orchestation.toString());
	}

	/**
	 * Set value of Effort_Orchestation
	 * @param effort_orchestation
	 */
	public final void setEffort_Orchestation(java.math.BigDecimal effort_orchestation)
	{
		setEffort_Orchestation(getContext(), effort_orchestation);
	}

	/**
	 * Set value of Effort_Orchestation
	 * @param context
	 * @param effort_orchestation
	 */
	public final void setEffort_Orchestation(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal effort_orchestation)
	{
		getMendixObject().setValue(context, MemberNames.Effort_Orchestation.toString(), effort_orchestation);
	}

	/**
	 * @return value of Assumptions_Template
	 */
	public final myfirstmodule.proxies.Template getAssumptions_Template() throws com.mendix.core.CoreException
	{
		return getAssumptions_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Assumptions_Template
	 */
	public final myfirstmodule.proxies.Template getAssumptions_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Assumptions_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Assumptions_Template
	 * @param assumptions_template
	 */
	public final void setAssumptions_Template(myfirstmodule.proxies.Template assumptions_template)
	{
		setAssumptions_Template(getContext(), assumptions_template);
	}

	/**
	 * Set value of Assumptions_Template
	 * @param context
	 * @param assumptions_template
	 */
	public final void setAssumptions_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template assumptions_template)
	{
		if (assumptions_template == null)
			getMendixObject().setValue(context, MemberNames.Assumptions_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Assumptions_Template.toString(), assumptions_template.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assumptionsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Assumptions that = (myfirstmodule.proxies.Assumptions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Assumptions";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
