// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Data_Based_Service
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject data_Based_ServiceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Data_Based_Service";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		No_of_Response_Parameter("No_of_Response_Parameter"),
		CoExist_with_Monolithic("CoExist_with_Monolithic"),
		Versioning("Versioning"),
		Service_Overlap("Service_Overlap"),
		Blocking_the_case("Blocking_the_case"),
		Consumer("Consumer"),
		Bussiness_Logic_Nature("Bussiness_Logic_Nature"),
		Database_Per_Service("Database_Per_Service"),
		Distributed_transaction("Distributed_transaction"),
		Event_base_Transaction("Event_base_Transaction"),
		Separate_Read_Write_Model("Separate_Read_Write_Model"),
		Complexity("Complexity"),
		Complexity_In_Percentage("Complexity_In_Percentage"),
		Template_Name("Template_Name"),
		UC("UC"),
		UseCase("UseCase"),
		Development("Development"),
		Service_Type("Service_Type"),
		Output_Format("Output_Format"),
		Service_Name("Service_Name"),
		Total_Complexity("Total_Complexity"),
		No_of_Request_Parameter("No_of_Request_Parameter"),
		Data_Based_Resource_Template("MyFirstModule.Data_Based_Resource_Template"),
		Data_Based_Service_Data_Based_SAV_Dev("MyFirstModule.Data_Based_Service_Data_Based_SAV_Dev"),
		Data_Based_Service_Data_Based_SAV_service("MyFirstModule.Data_Based_Service_Data_Based_SAV_service"),
		Data_Based_Service_Data_Based_SAV_output("MyFirstModule.Data_Based_Service_Data_Based_SAV_output");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Data_Based_Service(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Data_Based_Service"));
	}

	protected Data_Based_Service(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject data_Based_ServiceMendixObject)
	{
		if (data_Based_ServiceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Data_Based_Service", data_Based_ServiceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Data_Based_Service");

		this.data_Based_ServiceMendixObject = data_Based_ServiceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Data_Based_Service.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Data_Based_Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Data_Based_Service.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Data_Based_Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Data_Based_Service(context, mendixObject);
	}

	public static myfirstmodule.proxies.Data_Based_Service load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Data_Based_Service.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Data_Based_Service> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Data_Based_Service> result = new java.util.ArrayList<myfirstmodule.proxies.Data_Based_Service>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Data_Based_Service" + xpathConstraint))
			result.add(myfirstmodule.proxies.Data_Based_Service.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of No_of_Response_Parameter
	 */
	public final java.lang.Integer getNo_of_Response_Parameter()
	{
		return getNo_of_Response_Parameter(getContext());
	}

	/**
	 * @param context
	 * @return value of No_of_Response_Parameter
	 */
	public final java.lang.Integer getNo_of_Response_Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_of_Response_Parameter.toString());
	}

	/**
	 * Set value of No_of_Response_Parameter
	 * @param no_of_response_parameter
	 */
	public final void setNo_of_Response_Parameter(java.lang.Integer no_of_response_parameter)
	{
		setNo_of_Response_Parameter(getContext(), no_of_response_parameter);
	}

	/**
	 * Set value of No_of_Response_Parameter
	 * @param context
	 * @param no_of_response_parameter
	 */
	public final void setNo_of_Response_Parameter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_response_parameter)
	{
		getMendixObject().setValue(context, MemberNames.No_of_Response_Parameter.toString(), no_of_response_parameter);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param coexist_with_monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getCoExist_with_Monolithic()
	{
		return getCoExist_with_Monolithic(getContext());
	}

	/**
	 * @param context
	 * @return value of CoExist_with_Monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getCoExist_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CoExist_with_Monolithic.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param coexist_with_monolithic
	 */
	public final void setCoExist_with_Monolithic(myfirstmodule.proxies.Yes_No coexist_with_monolithic)
	{
		setCoExist_with_Monolithic(getContext(), coexist_with_monolithic);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param context
	 * @param coexist_with_monolithic
	 */
	public final void setCoExist_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No coexist_with_monolithic)
	{
		if (coexist_with_monolithic != null)
			getMendixObject().setValue(context, MemberNames.CoExist_with_Monolithic.toString(), coexist_with_monolithic.toString());
		else
			getMendixObject().setValue(context, MemberNames.CoExist_with_Monolithic.toString(), null);
	}

	/**
	 * Set value of Versioning
	 * @param versioning
	 */
	public final myfirstmodule.proxies.Yes_No getVersioning()
	{
		return getVersioning(getContext());
	}

	/**
	 * @param context
	 * @return value of Versioning
	 */
	public final myfirstmodule.proxies.Yes_No getVersioning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Versioning.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Versioning
	 * @param versioning
	 */
	public final void setVersioning(myfirstmodule.proxies.Yes_No versioning)
	{
		setVersioning(getContext(), versioning);
	}

	/**
	 * Set value of Versioning
	 * @param context
	 * @param versioning
	 */
	public final void setVersioning(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No versioning)
	{
		if (versioning != null)
			getMendixObject().setValue(context, MemberNames.Versioning.toString(), versioning.toString());
		else
			getMendixObject().setValue(context, MemberNames.Versioning.toString(), null);
	}

	/**
	 * Set value of Service_Overlap
	 * @param service_overlap
	 */
	public final myfirstmodule.proxies.Yes_No getService_Overlap()
	{
		return getService_Overlap(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Overlap
	 */
	public final myfirstmodule.proxies.Yes_No getService_Overlap(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Service_Overlap.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Service_Overlap
	 * @param service_overlap
	 */
	public final void setService_Overlap(myfirstmodule.proxies.Yes_No service_overlap)
	{
		setService_Overlap(getContext(), service_overlap);
	}

	/**
	 * Set value of Service_Overlap
	 * @param context
	 * @param service_overlap
	 */
	public final void setService_Overlap(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No service_overlap)
	{
		if (service_overlap != null)
			getMendixObject().setValue(context, MemberNames.Service_Overlap.toString(), service_overlap.toString());
		else
			getMendixObject().setValue(context, MemberNames.Service_Overlap.toString(), null);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param blocking_the_case
	 */
	public final myfirstmodule.proxies.Blocking_the_case getBlocking_the_case()
	{
		return getBlocking_the_case(getContext());
	}

	/**
	 * @param context
	 * @return value of Blocking_the_case
	 */
	public final myfirstmodule.proxies.Blocking_the_case getBlocking_the_case(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Blocking_the_case.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Blocking_the_case.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param blocking_the_case
	 */
	public final void setBlocking_the_case(myfirstmodule.proxies.Blocking_the_case blocking_the_case)
	{
		setBlocking_the_case(getContext(), blocking_the_case);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param context
	 * @param blocking_the_case
	 */
	public final void setBlocking_the_case(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Blocking_the_case blocking_the_case)
	{
		if (blocking_the_case != null)
			getMendixObject().setValue(context, MemberNames.Blocking_the_case.toString(), blocking_the_case.toString());
		else
			getMendixObject().setValue(context, MemberNames.Blocking_the_case.toString(), null);
	}

	/**
	 * Set value of Consumer
	 * @param consumer
	 */
	public final myfirstmodule.proxies.Consumers getConsumer()
	{
		return getConsumer(getContext());
	}

	/**
	 * @param context
	 * @return value of Consumer
	 */
	public final myfirstmodule.proxies.Consumers getConsumer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Consumer.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Consumers.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Consumer
	 * @param consumer
	 */
	public final void setConsumer(myfirstmodule.proxies.Consumers consumer)
	{
		setConsumer(getContext(), consumer);
	}

	/**
	 * Set value of Consumer
	 * @param context
	 * @param consumer
	 */
	public final void setConsumer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Consumers consumer)
	{
		if (consumer != null)
			getMendixObject().setValue(context, MemberNames.Consumer.toString(), consumer.toString());
		else
			getMendixObject().setValue(context, MemberNames.Consumer.toString(), null);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param bussiness_logic_nature
	 */
	public final myfirstmodule.proxies.Bussiness_Logic_Nature getBussiness_Logic_Nature()
	{
		return getBussiness_Logic_Nature(getContext());
	}

	/**
	 * @param context
	 * @return value of Bussiness_Logic_Nature
	 */
	public final myfirstmodule.proxies.Bussiness_Logic_Nature getBussiness_Logic_Nature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Bussiness_Logic_Nature.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Bussiness_Logic_Nature.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param bussiness_logic_nature
	 */
	public final void setBussiness_Logic_Nature(myfirstmodule.proxies.Bussiness_Logic_Nature bussiness_logic_nature)
	{
		setBussiness_Logic_Nature(getContext(), bussiness_logic_nature);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param context
	 * @param bussiness_logic_nature
	 */
	public final void setBussiness_Logic_Nature(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Bussiness_Logic_Nature bussiness_logic_nature)
	{
		if (bussiness_logic_nature != null)
			getMendixObject().setValue(context, MemberNames.Bussiness_Logic_Nature.toString(), bussiness_logic_nature.toString());
		else
			getMendixObject().setValue(context, MemberNames.Bussiness_Logic_Nature.toString(), null);
	}

	/**
	 * Set value of Database_Per_Service
	 * @param database_per_service
	 */
	public final myfirstmodule.proxies.Yes_No getDatabase_Per_Service()
	{
		return getDatabase_Per_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of Database_Per_Service
	 */
	public final myfirstmodule.proxies.Yes_No getDatabase_Per_Service(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Database_Per_Service.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Database_Per_Service
	 * @param database_per_service
	 */
	public final void setDatabase_Per_Service(myfirstmodule.proxies.Yes_No database_per_service)
	{
		setDatabase_Per_Service(getContext(), database_per_service);
	}

	/**
	 * Set value of Database_Per_Service
	 * @param context
	 * @param database_per_service
	 */
	public final void setDatabase_Per_Service(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No database_per_service)
	{
		if (database_per_service != null)
			getMendixObject().setValue(context, MemberNames.Database_Per_Service.toString(), database_per_service.toString());
		else
			getMendixObject().setValue(context, MemberNames.Database_Per_Service.toString(), null);
	}

	/**
	 * Set value of Distributed_transaction
	 * @param distributed_transaction
	 */
	public final myfirstmodule.proxies.Yes_No getDistributed_transaction()
	{
		return getDistributed_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of Distributed_transaction
	 */
	public final myfirstmodule.proxies.Yes_No getDistributed_transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Distributed_transaction.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Distributed_transaction
	 * @param distributed_transaction
	 */
	public final void setDistributed_transaction(myfirstmodule.proxies.Yes_No distributed_transaction)
	{
		setDistributed_transaction(getContext(), distributed_transaction);
	}

	/**
	 * Set value of Distributed_transaction
	 * @param context
	 * @param distributed_transaction
	 */
	public final void setDistributed_transaction(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No distributed_transaction)
	{
		if (distributed_transaction != null)
			getMendixObject().setValue(context, MemberNames.Distributed_transaction.toString(), distributed_transaction.toString());
		else
			getMendixObject().setValue(context, MemberNames.Distributed_transaction.toString(), null);
	}

	/**
	 * Set value of Event_base_Transaction
	 * @param event_base_transaction
	 */
	public final myfirstmodule.proxies.Yes_No getEvent_base_Transaction()
	{
		return getEvent_base_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_base_Transaction
	 */
	public final myfirstmodule.proxies.Yes_No getEvent_base_Transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Event_base_Transaction.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Event_base_Transaction
	 * @param event_base_transaction
	 */
	public final void setEvent_base_Transaction(myfirstmodule.proxies.Yes_No event_base_transaction)
	{
		setEvent_base_Transaction(getContext(), event_base_transaction);
	}

	/**
	 * Set value of Event_base_Transaction
	 * @param context
	 * @param event_base_transaction
	 */
	public final void setEvent_base_Transaction(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No event_base_transaction)
	{
		if (event_base_transaction != null)
			getMendixObject().setValue(context, MemberNames.Event_base_Transaction.toString(), event_base_transaction.toString());
		else
			getMendixObject().setValue(context, MemberNames.Event_base_Transaction.toString(), null);
	}

	/**
	 * Set value of Separate_Read_Write_Model
	 * @param separate_read_write_model
	 */
	public final myfirstmodule.proxies.Yes_No getSeparate_Read_Write_Model()
	{
		return getSeparate_Read_Write_Model(getContext());
	}

	/**
	 * @param context
	 * @return value of Separate_Read_Write_Model
	 */
	public final myfirstmodule.proxies.Yes_No getSeparate_Read_Write_Model(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Separate_Read_Write_Model.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Separate_Read_Write_Model
	 * @param separate_read_write_model
	 */
	public final void setSeparate_Read_Write_Model(myfirstmodule.proxies.Yes_No separate_read_write_model)
	{
		setSeparate_Read_Write_Model(getContext(), separate_read_write_model);
	}

	/**
	 * Set value of Separate_Read_Write_Model
	 * @param context
	 * @param separate_read_write_model
	 */
	public final void setSeparate_Read_Write_Model(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No separate_read_write_model)
	{
		if (separate_read_write_model != null)
			getMendixObject().setValue(context, MemberNames.Separate_Read_Write_Model.toString(), separate_read_write_model.toString());
		else
			getMendixObject().setValue(context, MemberNames.Separate_Read_Write_Model.toString(), null);
	}

	/**
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity()
	{
		return getComplexity(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity.toString());
	}

	/**
	 * Set value of Complexity
	 * @param complexity
	 */
	public final void setComplexity(java.math.BigDecimal complexity)
	{
		setComplexity(getContext(), complexity);
	}

	/**
	 * Set value of Complexity
	 * @param context
	 * @param complexity
	 */
	public final void setComplexity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity)
	{
		getMendixObject().setValue(context, MemberNames.Complexity.toString(), complexity);
	}

	/**
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage()
	{
		return getComplexity_In_Percentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity_In_Percentage.toString());
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(java.math.BigDecimal complexity_in_percentage)
	{
		setComplexity_In_Percentage(getContext(), complexity_in_percentage);
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param context
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity_in_percentage)
	{
		getMendixObject().setValue(context, MemberNames.Complexity_In_Percentage.toString(), complexity_in_percentage);
	}

	/**
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name()
	{
		return getTemplate_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Name.toString());
	}

	/**
	 * Set value of Template_Name
	 * @param template_name
	 */
	public final void setTemplate_Name(java.lang.String template_name)
	{
		setTemplate_Name(getContext(), template_name);
	}

	/**
	 * Set value of Template_Name
	 * @param context
	 * @param template_name
	 */
	public final void setTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_name)
	{
		getMendixObject().setValue(context, MemberNames.Template_Name.toString(), template_name);
	}

	/**
	 * @return value of UC
	 */
	public final java.lang.Long getUC()
	{
		return getUC(getContext());
	}

	/**
	 * @param context
	 * @return value of UC
	 */
	public final java.lang.Long getUC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UC.toString());
	}

	/**
	 * Set value of UC
	 * @param uc
	 */
	public final void setUC(java.lang.Long uc)
	{
		setUC(getContext(), uc);
	}

	/**
	 * Set value of UC
	 * @param context
	 * @param uc
	 */
	public final void setUC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long uc)
	{
		getMendixObject().setValue(context, MemberNames.UC.toString(), uc);
	}

	/**
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase()
	{
		return getUseCase(getContext());
	}

	/**
	 * @param context
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseCase.toString());
	}

	/**
	 * Set value of UseCase
	 * @param usecase
	 */
	public final void setUseCase(java.lang.String usecase)
	{
		setUseCase(getContext(), usecase);
	}

	/**
	 * Set value of UseCase
	 * @param context
	 * @param usecase
	 */
	public final void setUseCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usecase)
	{
		getMendixObject().setValue(context, MemberNames.UseCase.toString(), usecase);
	}

	/**
	 * @return value of Development
	 */
	public final java.lang.String getDevelopment()
	{
		return getDevelopment(getContext());
	}

	/**
	 * @param context
	 * @return value of Development
	 */
	public final java.lang.String getDevelopment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Development.toString());
	}

	/**
	 * Set value of Development
	 * @param development
	 */
	public final void setDevelopment(java.lang.String development)
	{
		setDevelopment(getContext(), development);
	}

	/**
	 * Set value of Development
	 * @param context
	 * @param development
	 */
	public final void setDevelopment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String development)
	{
		getMendixObject().setValue(context, MemberNames.Development.toString(), development);
	}

	/**
	 * @return value of Service_Type
	 */
	public final java.lang.String getService_Type()
	{
		return getService_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Type
	 */
	public final java.lang.String getService_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Type.toString());
	}

	/**
	 * Set value of Service_Type
	 * @param service_type
	 */
	public final void setService_Type(java.lang.String service_type)
	{
		setService_Type(getContext(), service_type);
	}

	/**
	 * Set value of Service_Type
	 * @param context
	 * @param service_type
	 */
	public final void setService_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_type)
	{
		getMendixObject().setValue(context, MemberNames.Service_Type.toString(), service_type);
	}

	/**
	 * @return value of Output_Format
	 */
	public final java.lang.String getOutput_Format()
	{
		return getOutput_Format(getContext());
	}

	/**
	 * @param context
	 * @return value of Output_Format
	 */
	public final java.lang.String getOutput_Format(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Output_Format.toString());
	}

	/**
	 * Set value of Output_Format
	 * @param output_format
	 */
	public final void setOutput_Format(java.lang.String output_format)
	{
		setOutput_Format(getContext(), output_format);
	}

	/**
	 * Set value of Output_Format
	 * @param context
	 * @param output_format
	 */
	public final void setOutput_Format(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String output_format)
	{
		getMendixObject().setValue(context, MemberNames.Output_Format.toString(), output_format);
	}

	/**
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name()
	{
		return getService_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Name.toString());
	}

	/**
	 * Set value of Service_Name
	 * @param service_name
	 */
	public final void setService_Name(java.lang.String service_name)
	{
		setService_Name(getContext(), service_name);
	}

	/**
	 * Set value of Service_Name
	 * @param context
	 * @param service_name
	 */
	public final void setService_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_Name.toString(), service_name);
	}

	/**
	 * @return value of Total_Complexity
	 */
	public final java.math.BigDecimal getTotal_Complexity()
	{
		return getTotal_Complexity(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_Complexity
	 */
	public final java.math.BigDecimal getTotal_Complexity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Total_Complexity.toString());
	}

	/**
	 * Set value of Total_Complexity
	 * @param total_complexity
	 */
	public final void setTotal_Complexity(java.math.BigDecimal total_complexity)
	{
		setTotal_Complexity(getContext(), total_complexity);
	}

	/**
	 * Set value of Total_Complexity
	 * @param context
	 * @param total_complexity
	 */
	public final void setTotal_Complexity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal total_complexity)
	{
		getMendixObject().setValue(context, MemberNames.Total_Complexity.toString(), total_complexity);
	}

	/**
	 * @return value of No_of_Request_Parameter
	 */
	public final java.lang.Integer getNo_of_Request_Parameter()
	{
		return getNo_of_Request_Parameter(getContext());
	}

	/**
	 * @param context
	 * @return value of No_of_Request_Parameter
	 */
	public final java.lang.Integer getNo_of_Request_Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_of_Request_Parameter.toString());
	}

	/**
	 * Set value of No_of_Request_Parameter
	 * @param no_of_request_parameter
	 */
	public final void setNo_of_Request_Parameter(java.lang.Integer no_of_request_parameter)
	{
		setNo_of_Request_Parameter(getContext(), no_of_request_parameter);
	}

	/**
	 * Set value of No_of_Request_Parameter
	 * @param context
	 * @param no_of_request_parameter
	 */
	public final void setNo_of_Request_Parameter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_request_parameter)
	{
		getMendixObject().setValue(context, MemberNames.No_of_Request_Parameter.toString(), no_of_request_parameter);
	}

	/**
	 * @return value of Data_Based_Resource_Template
	 */
	public final myfirstmodule.proxies.Template getData_Based_Resource_Template() throws com.mendix.core.CoreException
	{
		return getData_Based_Resource_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Based_Resource_Template
	 */
	public final myfirstmodule.proxies.Template getData_Based_Resource_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Based_Resource_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Based_Resource_Template
	 * @param data_based_resource_template
	 */
	public final void setData_Based_Resource_Template(myfirstmodule.proxies.Template data_based_resource_template)
	{
		setData_Based_Resource_Template(getContext(), data_based_resource_template);
	}

	/**
	 * Set value of Data_Based_Resource_Template
	 * @param context
	 * @param data_based_resource_template
	 */
	public final void setData_Based_Resource_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template data_based_resource_template)
	{
		if (data_based_resource_template == null)
			getMendixObject().setValue(context, MemberNames.Data_Based_Resource_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Based_Resource_Template.toString(), data_based_resource_template.getMendixObject().getId());
	}

	/**
	 * @return value of Data_Based_Service_Data_Based_SAV_Dev
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_Dev() throws com.mendix.core.CoreException
	{
		return getData_Based_Service_Data_Based_SAV_Dev(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Based_Service_Data_Based_SAV_Dev
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_Dev(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Data_Based_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_Dev.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Data_Based_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_Dev
	 * @param data_based_service_data_based_sav_dev
	 */
	public final void setData_Based_Service_Data_Based_SAV_Dev(myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_dev)
	{
		setData_Based_Service_Data_Based_SAV_Dev(getContext(), data_based_service_data_based_sav_dev);
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_Dev
	 * @param context
	 * @param data_based_service_data_based_sav_dev
	 */
	public final void setData_Based_Service_Data_Based_SAV_Dev(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_dev)
	{
		if (data_based_service_data_based_sav_dev == null)
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_Dev.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_Dev.toString(), data_based_service_data_based_sav_dev.getMendixObject().getId());
	}

	/**
	 * @return value of Data_Based_Service_Data_Based_SAV_service
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_service() throws com.mendix.core.CoreException
	{
		return getData_Based_Service_Data_Based_SAV_service(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Based_Service_Data_Based_SAV_service
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Data_Based_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_service.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Data_Based_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_service
	 * @param data_based_service_data_based_sav_service
	 */
	public final void setData_Based_Service_Data_Based_SAV_service(myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_service)
	{
		setData_Based_Service_Data_Based_SAV_service(getContext(), data_based_service_data_based_sav_service);
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_service
	 * @param context
	 * @param data_based_service_data_based_sav_service
	 */
	public final void setData_Based_Service_Data_Based_SAV_service(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_service)
	{
		if (data_based_service_data_based_sav_service == null)
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_service.toString(), data_based_service_data_based_sav_service.getMendixObject().getId());
	}

	/**
	 * @return value of Data_Based_Service_Data_Based_SAV_output
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_output() throws com.mendix.core.CoreException
	{
		return getData_Based_Service_Data_Based_SAV_output(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_Based_Service_Data_Based_SAV_output
	 */
	public final myfirstmodule.proxies.Data_Based_SAV getData_Based_Service_Data_Based_SAV_output(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Data_Based_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_output.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Data_Based_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_output
	 * @param data_based_service_data_based_sav_output
	 */
	public final void setData_Based_Service_Data_Based_SAV_output(myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_output)
	{
		setData_Based_Service_Data_Based_SAV_output(getContext(), data_based_service_data_based_sav_output);
	}

	/**
	 * Set value of Data_Based_Service_Data_Based_SAV_output
	 * @param context
	 * @param data_based_service_data_based_sav_output
	 */
	public final void setData_Based_Service_Data_Based_SAV_output(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Data_Based_SAV data_based_service_data_based_sav_output)
	{
		if (data_based_service_data_based_sav_output == null)
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_output.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Data_Based_Service_Data_Based_SAV_output.toString(), data_based_service_data_based_sav_output.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return data_Based_ServiceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Data_Based_Service that = (myfirstmodule.proxies.Data_Based_Service) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Data_Based_Service";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
