// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Development_Process
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject development_ProcessMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Development_Process";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UseCase("UseCase"),
		Service_name("Service_name"),
		Process("Process"),
		PairProgramming("PairProgramming"),
		Methodology("Methodology"),
		Dev_Environment("Dev_Environment"),
		Dev_Tool("Dev_Tool"),
		Testing_tool("Testing_tool"),
		Access("Access"),
		Branching_Strategy("Branching_Strategy"),
		Service_Writable_By("Service_Writable_By"),
		Complexity("Complexity"),
		Complexity_In_Percentage("Complexity_In_Percentage"),
		Documentation("Documentation"),
		Template_Name("Template_Name"),
		Development_Process_Template("MyFirstModule.Development_Process_Template"),
		Development_Process_Dev_process_SAV_pair("MyFirstModule.Development_Process_Dev_process_SAV_pair"),
		Development_Process_Dev_process_SAV_method("MyFirstModule.Development_Process_Dev_process_SAV_method"),
		Development_Process_Dev_process_SAV_env("MyFirstModule.Development_Process_Dev_process_SAV_env"),
		Development_Process_Dev_process_SAV_tool("MyFirstModule.Development_Process_Dev_process_SAV_tool"),
		Development_Process_Dev_process_SAV_testtool("MyFirstModule.Development_Process_Dev_process_SAV_testtool"),
		Development_Process_Dev_process_SAV_doc("MyFirstModule.Development_Process_Dev_process_SAV_doc"),
		Development_Process_Dev_process_SAV_Bus("MyFirstModule.Development_Process_Dev_process_SAV_Bus"),
		Development_Process_Dev_process_SAV_process("MyFirstModule.Development_Process_Dev_process_SAV_process");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Development_Process(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Development_Process"));
	}

	protected Development_Process(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject development_ProcessMendixObject)
	{
		if (development_ProcessMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Development_Process", development_ProcessMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Development_Process");

		this.development_ProcessMendixObject = development_ProcessMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Development_Process.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Development_Process initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Development_Process.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Development_Process initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Development_Process(context, mendixObject);
	}

	public static myfirstmodule.proxies.Development_Process load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Development_Process.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Development_Process> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Development_Process> result = new java.util.ArrayList<myfirstmodule.proxies.Development_Process>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Development_Process" + xpathConstraint))
			result.add(myfirstmodule.proxies.Development_Process.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase()
	{
		return getUseCase(getContext());
	}

	/**
	 * @param context
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseCase.toString());
	}

	/**
	 * Set value of UseCase
	 * @param usecase
	 */
	public final void setUseCase(java.lang.String usecase)
	{
		setUseCase(getContext(), usecase);
	}

	/**
	 * Set value of UseCase
	 * @param context
	 * @param usecase
	 */
	public final void setUseCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usecase)
	{
		getMendixObject().setValue(context, MemberNames.UseCase.toString(), usecase);
	}

	/**
	 * @return value of Service_name
	 */
	public final java.lang.String getService_name()
	{
		return getService_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_name
	 */
	public final java.lang.String getService_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_name.toString());
	}

	/**
	 * Set value of Service_name
	 * @param service_name
	 */
	public final void setService_name(java.lang.String service_name)
	{
		setService_name(getContext(), service_name);
	}

	/**
	 * Set value of Service_name
	 * @param context
	 * @param service_name
	 */
	public final void setService_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_name.toString(), service_name);
	}

	/**
	 * @return value of Process
	 */
	public final java.lang.String getProcess()
	{
		return getProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of Process
	 */
	public final java.lang.String getProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Process.toString());
	}

	/**
	 * Set value of Process
	 * @param process
	 */
	public final void setProcess(java.lang.String process)
	{
		setProcess(getContext(), process);
	}

	/**
	 * Set value of Process
	 * @param context
	 * @param process
	 */
	public final void setProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String process)
	{
		getMendixObject().setValue(context, MemberNames.Process.toString(), process);
	}

	/**
	 * Set value of PairProgramming
	 * @param pairprogramming
	 */
	public final myfirstmodule.proxies.Yes_No getPairProgramming()
	{
		return getPairProgramming(getContext());
	}

	/**
	 * @param context
	 * @return value of PairProgramming
	 */
	public final myfirstmodule.proxies.Yes_No getPairProgramming(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PairProgramming.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PairProgramming
	 * @param pairprogramming
	 */
	public final void setPairProgramming(myfirstmodule.proxies.Yes_No pairprogramming)
	{
		setPairProgramming(getContext(), pairprogramming);
	}

	/**
	 * Set value of PairProgramming
	 * @param context
	 * @param pairprogramming
	 */
	public final void setPairProgramming(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No pairprogramming)
	{
		if (pairprogramming != null)
			getMendixObject().setValue(context, MemberNames.PairProgramming.toString(), pairprogramming.toString());
		else
			getMendixObject().setValue(context, MemberNames.PairProgramming.toString(), null);
	}

	/**
	 * @return value of Methodology
	 */
	public final java.lang.String getMethodology()
	{
		return getMethodology(getContext());
	}

	/**
	 * @param context
	 * @return value of Methodology
	 */
	public final java.lang.String getMethodology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Methodology.toString());
	}

	/**
	 * Set value of Methodology
	 * @param methodology
	 */
	public final void setMethodology(java.lang.String methodology)
	{
		setMethodology(getContext(), methodology);
	}

	/**
	 * Set value of Methodology
	 * @param context
	 * @param methodology
	 */
	public final void setMethodology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String methodology)
	{
		getMendixObject().setValue(context, MemberNames.Methodology.toString(), methodology);
	}

	/**
	 * @return value of Dev_Environment
	 */
	public final java.lang.String getDev_Environment()
	{
		return getDev_Environment(getContext());
	}

	/**
	 * @param context
	 * @return value of Dev_Environment
	 */
	public final java.lang.String getDev_Environment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dev_Environment.toString());
	}

	/**
	 * Set value of Dev_Environment
	 * @param dev_environment
	 */
	public final void setDev_Environment(java.lang.String dev_environment)
	{
		setDev_Environment(getContext(), dev_environment);
	}

	/**
	 * Set value of Dev_Environment
	 * @param context
	 * @param dev_environment
	 */
	public final void setDev_Environment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dev_environment)
	{
		getMendixObject().setValue(context, MemberNames.Dev_Environment.toString(), dev_environment);
	}

	/**
	 * @return value of Dev_Tool
	 */
	public final java.lang.String getDev_Tool()
	{
		return getDev_Tool(getContext());
	}

	/**
	 * @param context
	 * @return value of Dev_Tool
	 */
	public final java.lang.String getDev_Tool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dev_Tool.toString());
	}

	/**
	 * Set value of Dev_Tool
	 * @param dev_tool
	 */
	public final void setDev_Tool(java.lang.String dev_tool)
	{
		setDev_Tool(getContext(), dev_tool);
	}

	/**
	 * Set value of Dev_Tool
	 * @param context
	 * @param dev_tool
	 */
	public final void setDev_Tool(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dev_tool)
	{
		getMendixObject().setValue(context, MemberNames.Dev_Tool.toString(), dev_tool);
	}

	/**
	 * @return value of Testing_tool
	 */
	public final java.lang.String getTesting_tool()
	{
		return getTesting_tool(getContext());
	}

	/**
	 * @param context
	 * @return value of Testing_tool
	 */
	public final java.lang.String getTesting_tool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Testing_tool.toString());
	}

	/**
	 * Set value of Testing_tool
	 * @param testing_tool
	 */
	public final void setTesting_tool(java.lang.String testing_tool)
	{
		setTesting_tool(getContext(), testing_tool);
	}

	/**
	 * Set value of Testing_tool
	 * @param context
	 * @param testing_tool
	 */
	public final void setTesting_tool(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String testing_tool)
	{
		getMendixObject().setValue(context, MemberNames.Testing_tool.toString(), testing_tool);
	}

	/**
	 * Set value of Access
	 * @param access
	 */
	public final myfirstmodule.proxies.Open_CloseAccess getAccess()
	{
		return getAccess(getContext());
	}

	/**
	 * @param context
	 * @return value of Access
	 */
	public final myfirstmodule.proxies.Open_CloseAccess getAccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Access.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Open_CloseAccess.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Access
	 * @param access
	 */
	public final void setAccess(myfirstmodule.proxies.Open_CloseAccess access)
	{
		setAccess(getContext(), access);
	}

	/**
	 * Set value of Access
	 * @param context
	 * @param access
	 */
	public final void setAccess(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Open_CloseAccess access)
	{
		if (access != null)
			getMendixObject().setValue(context, MemberNames.Access.toString(), access.toString());
		else
			getMendixObject().setValue(context, MemberNames.Access.toString(), null);
	}

	/**
	 * @return value of Branching_Strategy
	 */
	public final java.lang.String getBranching_Strategy()
	{
		return getBranching_Strategy(getContext());
	}

	/**
	 * @param context
	 * @return value of Branching_Strategy
	 */
	public final java.lang.String getBranching_Strategy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Branching_Strategy.toString());
	}

	/**
	 * Set value of Branching_Strategy
	 * @param branching_strategy
	 */
	public final void setBranching_Strategy(java.lang.String branching_strategy)
	{
		setBranching_Strategy(getContext(), branching_strategy);
	}

	/**
	 * Set value of Branching_Strategy
	 * @param context
	 * @param branching_strategy
	 */
	public final void setBranching_Strategy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String branching_strategy)
	{
		getMendixObject().setValue(context, MemberNames.Branching_Strategy.toString(), branching_strategy);
	}

	/**
	 * Set value of Service_Writable_By
	 * @param service_writable_by
	 */
	public final myfirstmodule.proxies.Team getService_Writable_By()
	{
		return getService_Writable_By(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Writable_By
	 */
	public final myfirstmodule.proxies.Team getService_Writable_By(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Service_Writable_By.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Team.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Service_Writable_By
	 * @param service_writable_by
	 */
	public final void setService_Writable_By(myfirstmodule.proxies.Team service_writable_by)
	{
		setService_Writable_By(getContext(), service_writable_by);
	}

	/**
	 * Set value of Service_Writable_By
	 * @param context
	 * @param service_writable_by
	 */
	public final void setService_Writable_By(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Team service_writable_by)
	{
		if (service_writable_by != null)
			getMendixObject().setValue(context, MemberNames.Service_Writable_By.toString(), service_writable_by.toString());
		else
			getMendixObject().setValue(context, MemberNames.Service_Writable_By.toString(), null);
	}

	/**
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity()
	{
		return getComplexity(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity.toString());
	}

	/**
	 * Set value of Complexity
	 * @param complexity
	 */
	public final void setComplexity(java.math.BigDecimal complexity)
	{
		setComplexity(getContext(), complexity);
	}

	/**
	 * Set value of Complexity
	 * @param context
	 * @param complexity
	 */
	public final void setComplexity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity)
	{
		getMendixObject().setValue(context, MemberNames.Complexity.toString(), complexity);
	}

	/**
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage()
	{
		return getComplexity_In_Percentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity_In_Percentage.toString());
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(java.math.BigDecimal complexity_in_percentage)
	{
		setComplexity_In_Percentage(getContext(), complexity_in_percentage);
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param context
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity_in_percentage)
	{
		getMendixObject().setValue(context, MemberNames.Complexity_In_Percentage.toString(), complexity_in_percentage);
	}

	/**
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation()
	{
		return getDocumentation(getContext());
	}

	/**
	 * @param context
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Documentation.toString());
	}

	/**
	 * Set value of Documentation
	 * @param documentation
	 */
	public final void setDocumentation(java.lang.String documentation)
	{
		setDocumentation(getContext(), documentation);
	}

	/**
	 * Set value of Documentation
	 * @param context
	 * @param documentation
	 */
	public final void setDocumentation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documentation)
	{
		getMendixObject().setValue(context, MemberNames.Documentation.toString(), documentation);
	}

	/**
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name()
	{
		return getTemplate_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Name.toString());
	}

	/**
	 * Set value of Template_Name
	 * @param template_name
	 */
	public final void setTemplate_Name(java.lang.String template_name)
	{
		setTemplate_Name(getContext(), template_name);
	}

	/**
	 * Set value of Template_Name
	 * @param context
	 * @param template_name
	 */
	public final void setTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_name)
	{
		getMendixObject().setValue(context, MemberNames.Template_Name.toString(), template_name);
	}

	/**
	 * @return value of Development_Process_Template
	 */
	public final myfirstmodule.proxies.Template getDevelopment_Process_Template() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Template
	 */
	public final myfirstmodule.proxies.Template getDevelopment_Process_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Template
	 * @param development_process_template
	 */
	public final void setDevelopment_Process_Template(myfirstmodule.proxies.Template development_process_template)
	{
		setDevelopment_Process_Template(getContext(), development_process_template);
	}

	/**
	 * Set value of Development_Process_Template
	 * @param context
	 * @param development_process_template
	 */
	public final void setDevelopment_Process_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template development_process_template)
	{
		if (development_process_template == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Template.toString(), development_process_template.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_pair
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_pair() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_pair(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_pair
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_pair(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_pair.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_pair
	 * @param development_process_dev_process_sav_pair
	 */
	public final void setDevelopment_Process_Dev_process_SAV_pair(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_pair)
	{
		setDevelopment_Process_Dev_process_SAV_pair(getContext(), development_process_dev_process_sav_pair);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_pair
	 * @param context
	 * @param development_process_dev_process_sav_pair
	 */
	public final void setDevelopment_Process_Dev_process_SAV_pair(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_pair)
	{
		if (development_process_dev_process_sav_pair == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_pair.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_pair.toString(), development_process_dev_process_sav_pair.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_method
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_method() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_method(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_method
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_method(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_method.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_method
	 * @param development_process_dev_process_sav_method
	 */
	public final void setDevelopment_Process_Dev_process_SAV_method(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_method)
	{
		setDevelopment_Process_Dev_process_SAV_method(getContext(), development_process_dev_process_sav_method);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_method
	 * @param context
	 * @param development_process_dev_process_sav_method
	 */
	public final void setDevelopment_Process_Dev_process_SAV_method(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_method)
	{
		if (development_process_dev_process_sav_method == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_method.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_method.toString(), development_process_dev_process_sav_method.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_env
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_env() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_env(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_env
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_env(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_env.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_env
	 * @param development_process_dev_process_sav_env
	 */
	public final void setDevelopment_Process_Dev_process_SAV_env(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_env)
	{
		setDevelopment_Process_Dev_process_SAV_env(getContext(), development_process_dev_process_sav_env);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_env
	 * @param context
	 * @param development_process_dev_process_sav_env
	 */
	public final void setDevelopment_Process_Dev_process_SAV_env(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_env)
	{
		if (development_process_dev_process_sav_env == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_env.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_env.toString(), development_process_dev_process_sav_env.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_tool
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_tool() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_tool(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_tool
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_tool(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_tool.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_tool
	 * @param development_process_dev_process_sav_tool
	 */
	public final void setDevelopment_Process_Dev_process_SAV_tool(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_tool)
	{
		setDevelopment_Process_Dev_process_SAV_tool(getContext(), development_process_dev_process_sav_tool);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_tool
	 * @param context
	 * @param development_process_dev_process_sav_tool
	 */
	public final void setDevelopment_Process_Dev_process_SAV_tool(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_tool)
	{
		if (development_process_dev_process_sav_tool == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_tool.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_tool.toString(), development_process_dev_process_sav_tool.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_testtool
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_testtool() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_testtool(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_testtool
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_testtool(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_testtool.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_testtool
	 * @param development_process_dev_process_sav_testtool
	 */
	public final void setDevelopment_Process_Dev_process_SAV_testtool(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_testtool)
	{
		setDevelopment_Process_Dev_process_SAV_testtool(getContext(), development_process_dev_process_sav_testtool);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_testtool
	 * @param context
	 * @param development_process_dev_process_sav_testtool
	 */
	public final void setDevelopment_Process_Dev_process_SAV_testtool(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_testtool)
	{
		if (development_process_dev_process_sav_testtool == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_testtool.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_testtool.toString(), development_process_dev_process_sav_testtool.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_doc
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_doc() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_doc(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_doc
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_doc(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_doc.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_doc
	 * @param development_process_dev_process_sav_doc
	 */
	public final void setDevelopment_Process_Dev_process_SAV_doc(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_doc)
	{
		setDevelopment_Process_Dev_process_SAV_doc(getContext(), development_process_dev_process_sav_doc);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_doc
	 * @param context
	 * @param development_process_dev_process_sav_doc
	 */
	public final void setDevelopment_Process_Dev_process_SAV_doc(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_doc)
	{
		if (development_process_dev_process_sav_doc == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_doc.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_doc.toString(), development_process_dev_process_sav_doc.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_Bus
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_Bus() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_Bus(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_Bus
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_Bus(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_Bus.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_Bus
	 * @param development_process_dev_process_sav_bus
	 */
	public final void setDevelopment_Process_Dev_process_SAV_Bus(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_bus)
	{
		setDevelopment_Process_Dev_process_SAV_Bus(getContext(), development_process_dev_process_sav_bus);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_Bus
	 * @param context
	 * @param development_process_dev_process_sav_bus
	 */
	public final void setDevelopment_Process_Dev_process_SAV_Bus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_bus)
	{
		if (development_process_dev_process_sav_bus == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_Bus.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_Bus.toString(), development_process_dev_process_sav_bus.getMendixObject().getId());
	}

	/**
	 * @return value of Development_Process_Dev_process_SAV_process
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_process() throws com.mendix.core.CoreException
	{
		return getDevelopment_Process_Dev_process_SAV_process(getContext());
	}

	/**
	 * @param context
	 * @return value of Development_Process_Dev_process_SAV_process
	 */
	public final myfirstmodule.proxies.Dev_process_SAV getDevelopment_Process_Dev_process_SAV_process(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Dev_process_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Development_Process_Dev_process_SAV_process.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Dev_process_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_process
	 * @param development_process_dev_process_sav_process
	 */
	public final void setDevelopment_Process_Dev_process_SAV_process(myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_process)
	{
		setDevelopment_Process_Dev_process_SAV_process(getContext(), development_process_dev_process_sav_process);
	}

	/**
	 * Set value of Development_Process_Dev_process_SAV_process
	 * @param context
	 * @param development_process_dev_process_sav_process
	 */
	public final void setDevelopment_Process_Dev_process_SAV_process(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dev_process_SAV development_process_dev_process_sav_process)
	{
		if (development_process_dev_process_sav_process == null)
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_process.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Development_Process_Dev_process_SAV_process.toString(), development_process_dev_process_sav_process.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return development_ProcessMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Development_Process that = (myfirstmodule.proxies.Development_Process) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Development_Process";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
