// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Enumeration_assump_service_type
{
	Service_Nature(new java.lang.String[][] { new java.lang.String[] { "en_US", "Service Nature" } }),
	Patterns___Practices(new java.lang.String[][] { new java.lang.String[] { "en_US", "Patterns & Practices" } }),
	Tech_stack(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tech stack" } }),
	Development_Process(new java.lang.String[][] { new java.lang.String[] { "en_US", "Development Process" } }),
	Policy(new java.lang.String[][] { new java.lang.String[] { "en_US", "Policy" } }),
	One_time_effort(new java.lang.String[][] { new java.lang.String[] { "en_US", "One time effort" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enumeration_assump_service_type(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
