// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Mode_of_Integration
{
	Sync(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sync" } }),
	Async(new java.lang.String[][] { new java.lang.String[] { "en_US", "Async" } }),
	Mixed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mixed" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Mode_of_Integration(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
