// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Orchestration_Service
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orchestration_ServiceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Orchestration_Service";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		No_of_Response_Parameter("No_of_Response_Parameter"),
		CoExist_with_Monolithic("CoExist_with_Monolithic"),
		Versioning("Versioning"),
		Service_Overlap("Service_Overlap"),
		Blocking_the_case("Blocking_the_case"),
		Consumers("Consumers"),
		Bussiness_Logic_Nature("Bussiness_Logic_Nature"),
		No_of_services_to_be_integrated("No_of_services_to_be_integrated"),
		Mode_of_Integration("Mode_of_Integration"),
		Implementation_Type("Implementation_Type"),
		Aggregate_Data("Aggregate_Data"),
		Cache_Response("Cache_Response"),
		Complexity("Complexity"),
		Complexity_In_Percentage("Complexity_In_Percentage"),
		Template_Name("Template_Name"),
		UC("UC"),
		UseCase("UseCase"),
		Development("Development"),
		Service_Type("Service_Type"),
		Output_Format("Output_Format"),
		__ID("__ID"),
		No_Of_Request_Parameter("No_Of_Request_Parameter"),
		Total_effort_PD("Total_effort_PD"),
		Total_effort_PD_Rounded("Total_effort_PD_Rounded"),
		Orchestration_total("Orchestration_total"),
		TotalEffort("TotalEffort"),
		Group_Name("Group_Name"),
		Orchestration_Service_Template("MyFirstModule.Orchestration_Service_Template"),
		Orchestration_Service_Service_Attribute("MyFirstModule.Orchestration_Service_Service_Attribute"),
		Orchestration_Service_Assumptions("MyFirstModule.Orchestration_Service_Assumptions"),
		Orchestration_Service_Orch_SAV_dev("MyFirstModule.Orchestration_Service_Orch_SAV_dev"),
		Orchestration_Service_Orch_SAV_svctype("MyFirstModule.Orchestration_Service_Orch_SAV_svctype"),
		Orchestration_Service_Orch_output("MyFirstModule.Orchestration_Service_Orch_output");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Orchestration_Service(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Orchestration_Service"));
	}

	protected Orchestration_Service(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orchestration_ServiceMendixObject)
	{
		if (orchestration_ServiceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Orchestration_Service", orchestration_ServiceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Orchestration_Service");

		this.orchestration_ServiceMendixObject = orchestration_ServiceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Orchestration_Service.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Orchestration_Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Orchestration_Service.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Orchestration_Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Orchestration_Service(context, mendixObject);
	}

	public static myfirstmodule.proxies.Orchestration_Service load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Orchestration_Service.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Orchestration_Service> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Orchestration_Service> result = new java.util.ArrayList<myfirstmodule.proxies.Orchestration_Service>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Orchestration_Service" + xpathConstraint))
			result.add(myfirstmodule.proxies.Orchestration_Service.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of No_of_Response_Parameter
	 */
	public final java.lang.Integer getNo_of_Response_Parameter()
	{
		return getNo_of_Response_Parameter(getContext());
	}

	/**
	 * @param context
	 * @return value of No_of_Response_Parameter
	 */
	public final java.lang.Integer getNo_of_Response_Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_of_Response_Parameter.toString());
	}

	/**
	 * Set value of No_of_Response_Parameter
	 * @param no_of_response_parameter
	 */
	public final void setNo_of_Response_Parameter(java.lang.Integer no_of_response_parameter)
	{
		setNo_of_Response_Parameter(getContext(), no_of_response_parameter);
	}

	/**
	 * Set value of No_of_Response_Parameter
	 * @param context
	 * @param no_of_response_parameter
	 */
	public final void setNo_of_Response_Parameter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_response_parameter)
	{
		getMendixObject().setValue(context, MemberNames.No_of_Response_Parameter.toString(), no_of_response_parameter);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param coexist_with_monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getCoExist_with_Monolithic()
	{
		return getCoExist_with_Monolithic(getContext());
	}

	/**
	 * @param context
	 * @return value of CoExist_with_Monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getCoExist_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CoExist_with_Monolithic.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param coexist_with_monolithic
	 */
	public final void setCoExist_with_Monolithic(myfirstmodule.proxies.Yes_No coexist_with_monolithic)
	{
		setCoExist_with_Monolithic(getContext(), coexist_with_monolithic);
	}

	/**
	 * Set value of CoExist_with_Monolithic
	 * @param context
	 * @param coexist_with_monolithic
	 */
	public final void setCoExist_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No coexist_with_monolithic)
	{
		if (coexist_with_monolithic != null)
			getMendixObject().setValue(context, MemberNames.CoExist_with_Monolithic.toString(), coexist_with_monolithic.toString());
		else
			getMendixObject().setValue(context, MemberNames.CoExist_with_Monolithic.toString(), null);
	}

	/**
	 * Set value of Versioning
	 * @param versioning
	 */
	public final myfirstmodule.proxies.Yes_No getVersioning()
	{
		return getVersioning(getContext());
	}

	/**
	 * @param context
	 * @return value of Versioning
	 */
	public final myfirstmodule.proxies.Yes_No getVersioning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Versioning.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Versioning
	 * @param versioning
	 */
	public final void setVersioning(myfirstmodule.proxies.Yes_No versioning)
	{
		setVersioning(getContext(), versioning);
	}

	/**
	 * Set value of Versioning
	 * @param context
	 * @param versioning
	 */
	public final void setVersioning(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No versioning)
	{
		if (versioning != null)
			getMendixObject().setValue(context, MemberNames.Versioning.toString(), versioning.toString());
		else
			getMendixObject().setValue(context, MemberNames.Versioning.toString(), null);
	}

	/**
	 * Set value of Service_Overlap
	 * @param service_overlap
	 */
	public final myfirstmodule.proxies.Yes_No getService_Overlap()
	{
		return getService_Overlap(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Overlap
	 */
	public final myfirstmodule.proxies.Yes_No getService_Overlap(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Service_Overlap.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Service_Overlap
	 * @param service_overlap
	 */
	public final void setService_Overlap(myfirstmodule.proxies.Yes_No service_overlap)
	{
		setService_Overlap(getContext(), service_overlap);
	}

	/**
	 * Set value of Service_Overlap
	 * @param context
	 * @param service_overlap
	 */
	public final void setService_Overlap(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No service_overlap)
	{
		if (service_overlap != null)
			getMendixObject().setValue(context, MemberNames.Service_Overlap.toString(), service_overlap.toString());
		else
			getMendixObject().setValue(context, MemberNames.Service_Overlap.toString(), null);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param blocking_the_case
	 */
	public final myfirstmodule.proxies.Blocking_the_case getBlocking_the_case()
	{
		return getBlocking_the_case(getContext());
	}

	/**
	 * @param context
	 * @return value of Blocking_the_case
	 */
	public final myfirstmodule.proxies.Blocking_the_case getBlocking_the_case(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Blocking_the_case.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Blocking_the_case.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param blocking_the_case
	 */
	public final void setBlocking_the_case(myfirstmodule.proxies.Blocking_the_case blocking_the_case)
	{
		setBlocking_the_case(getContext(), blocking_the_case);
	}

	/**
	 * Set value of Blocking_the_case
	 * @param context
	 * @param blocking_the_case
	 */
	public final void setBlocking_the_case(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Blocking_the_case blocking_the_case)
	{
		if (blocking_the_case != null)
			getMendixObject().setValue(context, MemberNames.Blocking_the_case.toString(), blocking_the_case.toString());
		else
			getMendixObject().setValue(context, MemberNames.Blocking_the_case.toString(), null);
	}

	/**
	 * Set value of Consumers
	 * @param consumers
	 */
	public final myfirstmodule.proxies.Consumers getConsumers()
	{
		return getConsumers(getContext());
	}

	/**
	 * @param context
	 * @return value of Consumers
	 */
	public final myfirstmodule.proxies.Consumers getConsumers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Consumers.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Consumers.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Consumers
	 * @param consumers
	 */
	public final void setConsumers(myfirstmodule.proxies.Consumers consumers)
	{
		setConsumers(getContext(), consumers);
	}

	/**
	 * Set value of Consumers
	 * @param context
	 * @param consumers
	 */
	public final void setConsumers(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Consumers consumers)
	{
		if (consumers != null)
			getMendixObject().setValue(context, MemberNames.Consumers.toString(), consumers.toString());
		else
			getMendixObject().setValue(context, MemberNames.Consumers.toString(), null);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param bussiness_logic_nature
	 */
	public final myfirstmodule.proxies.Bussiness_Logic_Nature getBussiness_Logic_Nature()
	{
		return getBussiness_Logic_Nature(getContext());
	}

	/**
	 * @param context
	 * @return value of Bussiness_Logic_Nature
	 */
	public final myfirstmodule.proxies.Bussiness_Logic_Nature getBussiness_Logic_Nature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Bussiness_Logic_Nature.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Bussiness_Logic_Nature.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param bussiness_logic_nature
	 */
	public final void setBussiness_Logic_Nature(myfirstmodule.proxies.Bussiness_Logic_Nature bussiness_logic_nature)
	{
		setBussiness_Logic_Nature(getContext(), bussiness_logic_nature);
	}

	/**
	 * Set value of Bussiness_Logic_Nature
	 * @param context
	 * @param bussiness_logic_nature
	 */
	public final void setBussiness_Logic_Nature(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Bussiness_Logic_Nature bussiness_logic_nature)
	{
		if (bussiness_logic_nature != null)
			getMendixObject().setValue(context, MemberNames.Bussiness_Logic_Nature.toString(), bussiness_logic_nature.toString());
		else
			getMendixObject().setValue(context, MemberNames.Bussiness_Logic_Nature.toString(), null);
	}

	/**
	 * @return value of No_of_services_to_be_integrated
	 */
	public final java.lang.Integer getNo_of_services_to_be_integrated()
	{
		return getNo_of_services_to_be_integrated(getContext());
	}

	/**
	 * @param context
	 * @return value of No_of_services_to_be_integrated
	 */
	public final java.lang.Integer getNo_of_services_to_be_integrated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_of_services_to_be_integrated.toString());
	}

	/**
	 * Set value of No_of_services_to_be_integrated
	 * @param no_of_services_to_be_integrated
	 */
	public final void setNo_of_services_to_be_integrated(java.lang.Integer no_of_services_to_be_integrated)
	{
		setNo_of_services_to_be_integrated(getContext(), no_of_services_to_be_integrated);
	}

	/**
	 * Set value of No_of_services_to_be_integrated
	 * @param context
	 * @param no_of_services_to_be_integrated
	 */
	public final void setNo_of_services_to_be_integrated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_services_to_be_integrated)
	{
		getMendixObject().setValue(context, MemberNames.No_of_services_to_be_integrated.toString(), no_of_services_to_be_integrated);
	}

	/**
	 * Set value of Mode_of_Integration
	 * @param mode_of_integration
	 */
	public final myfirstmodule.proxies.Mode_of_Integration getMode_of_Integration()
	{
		return getMode_of_Integration(getContext());
	}

	/**
	 * @param context
	 * @return value of Mode_of_Integration
	 */
	public final myfirstmodule.proxies.Mode_of_Integration getMode_of_Integration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Mode_of_Integration.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Mode_of_Integration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Mode_of_Integration
	 * @param mode_of_integration
	 */
	public final void setMode_of_Integration(myfirstmodule.proxies.Mode_of_Integration mode_of_integration)
	{
		setMode_of_Integration(getContext(), mode_of_integration);
	}

	/**
	 * Set value of Mode_of_Integration
	 * @param context
	 * @param mode_of_integration
	 */
	public final void setMode_of_Integration(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Mode_of_Integration mode_of_integration)
	{
		if (mode_of_integration != null)
			getMendixObject().setValue(context, MemberNames.Mode_of_Integration.toString(), mode_of_integration.toString());
		else
			getMendixObject().setValue(context, MemberNames.Mode_of_Integration.toString(), null);
	}

	/**
	 * Set value of Implementation_Type
	 * @param implementation_type
	 */
	public final myfirstmodule.proxies.Implementation_Type getImplementation_Type()
	{
		return getImplementation_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Implementation_Type
	 */
	public final myfirstmodule.proxies.Implementation_Type getImplementation_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Implementation_Type.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Implementation_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Implementation_Type
	 * @param implementation_type
	 */
	public final void setImplementation_Type(myfirstmodule.proxies.Implementation_Type implementation_type)
	{
		setImplementation_Type(getContext(), implementation_type);
	}

	/**
	 * Set value of Implementation_Type
	 * @param context
	 * @param implementation_type
	 */
	public final void setImplementation_Type(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Implementation_Type implementation_type)
	{
		if (implementation_type != null)
			getMendixObject().setValue(context, MemberNames.Implementation_Type.toString(), implementation_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.Implementation_Type.toString(), null);
	}

	/**
	 * Set value of Aggregate_Data
	 * @param aggregate_data
	 */
	public final myfirstmodule.proxies.Yes_No getAggregate_Data()
	{
		return getAggregate_Data(getContext());
	}

	/**
	 * @param context
	 * @return value of Aggregate_Data
	 */
	public final myfirstmodule.proxies.Yes_No getAggregate_Data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Aggregate_Data.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Aggregate_Data
	 * @param aggregate_data
	 */
	public final void setAggregate_Data(myfirstmodule.proxies.Yes_No aggregate_data)
	{
		setAggregate_Data(getContext(), aggregate_data);
	}

	/**
	 * Set value of Aggregate_Data
	 * @param context
	 * @param aggregate_data
	 */
	public final void setAggregate_Data(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No aggregate_data)
	{
		if (aggregate_data != null)
			getMendixObject().setValue(context, MemberNames.Aggregate_Data.toString(), aggregate_data.toString());
		else
			getMendixObject().setValue(context, MemberNames.Aggregate_Data.toString(), null);
	}

	/**
	 * Set value of Cache_Response
	 * @param cache_response
	 */
	public final myfirstmodule.proxies.Yes_No getCache_Response()
	{
		return getCache_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of Cache_Response
	 */
	public final myfirstmodule.proxies.Yes_No getCache_Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Cache_Response.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Cache_Response
	 * @param cache_response
	 */
	public final void setCache_Response(myfirstmodule.proxies.Yes_No cache_response)
	{
		setCache_Response(getContext(), cache_response);
	}

	/**
	 * Set value of Cache_Response
	 * @param context
	 * @param cache_response
	 */
	public final void setCache_Response(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No cache_response)
	{
		if (cache_response != null)
			getMendixObject().setValue(context, MemberNames.Cache_Response.toString(), cache_response.toString());
		else
			getMendixObject().setValue(context, MemberNames.Cache_Response.toString(), null);
	}

	/**
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity()
	{
		return getComplexity(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity.toString());
	}

	/**
	 * Set value of Complexity
	 * @param complexity
	 */
	public final void setComplexity(java.math.BigDecimal complexity)
	{
		setComplexity(getContext(), complexity);
	}

	/**
	 * Set value of Complexity
	 * @param context
	 * @param complexity
	 */
	public final void setComplexity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity)
	{
		getMendixObject().setValue(context, MemberNames.Complexity.toString(), complexity);
	}

	/**
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage()
	{
		return getComplexity_In_Percentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity_In_Percentage.toString());
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(java.math.BigDecimal complexity_in_percentage)
	{
		setComplexity_In_Percentage(getContext(), complexity_in_percentage);
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param context
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity_in_percentage)
	{
		getMendixObject().setValue(context, MemberNames.Complexity_In_Percentage.toString(), complexity_in_percentage);
	}

	/**
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name()
	{
		return getTemplate_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Name.toString());
	}

	/**
	 * Set value of Template_Name
	 * @param template_name
	 */
	public final void setTemplate_Name(java.lang.String template_name)
	{
		setTemplate_Name(getContext(), template_name);
	}

	/**
	 * Set value of Template_Name
	 * @param context
	 * @param template_name
	 */
	public final void setTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_name)
	{
		getMendixObject().setValue(context, MemberNames.Template_Name.toString(), template_name);
	}

	/**
	 * @return value of UC
	 */
	public final java.lang.Long getUC()
	{
		return getUC(getContext());
	}

	/**
	 * @param context
	 * @return value of UC
	 */
	public final java.lang.Long getUC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UC.toString());
	}

	/**
	 * Set value of UC
	 * @param uc
	 */
	public final void setUC(java.lang.Long uc)
	{
		setUC(getContext(), uc);
	}

	/**
	 * Set value of UC
	 * @param context
	 * @param uc
	 */
	public final void setUC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long uc)
	{
		getMendixObject().setValue(context, MemberNames.UC.toString(), uc);
	}

	/**
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase()
	{
		return getUseCase(getContext());
	}

	/**
	 * @param context
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseCase.toString());
	}

	/**
	 * Set value of UseCase
	 * @param usecase
	 */
	public final void setUseCase(java.lang.String usecase)
	{
		setUseCase(getContext(), usecase);
	}

	/**
	 * Set value of UseCase
	 * @param context
	 * @param usecase
	 */
	public final void setUseCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usecase)
	{
		getMendixObject().setValue(context, MemberNames.UseCase.toString(), usecase);
	}

	/**
	 * @return value of Development
	 */
	public final java.lang.String getDevelopment()
	{
		return getDevelopment(getContext());
	}

	/**
	 * @param context
	 * @return value of Development
	 */
	public final java.lang.String getDevelopment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Development.toString());
	}

	/**
	 * Set value of Development
	 * @param development
	 */
	public final void setDevelopment(java.lang.String development)
	{
		setDevelopment(getContext(), development);
	}

	/**
	 * Set value of Development
	 * @param context
	 * @param development
	 */
	public final void setDevelopment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String development)
	{
		getMendixObject().setValue(context, MemberNames.Development.toString(), development);
	}

	/**
	 * @return value of Service_Type
	 */
	public final java.lang.String getService_Type()
	{
		return getService_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Type
	 */
	public final java.lang.String getService_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Type.toString());
	}

	/**
	 * Set value of Service_Type
	 * @param service_type
	 */
	public final void setService_Type(java.lang.String service_type)
	{
		setService_Type(getContext(), service_type);
	}

	/**
	 * Set value of Service_Type
	 * @param context
	 * @param service_type
	 */
	public final void setService_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_type)
	{
		getMendixObject().setValue(context, MemberNames.Service_Type.toString(), service_type);
	}

	/**
	 * @return value of Output_Format
	 */
	public final java.lang.String getOutput_Format()
	{
		return getOutput_Format(getContext());
	}

	/**
	 * @param context
	 * @return value of Output_Format
	 */
	public final java.lang.String getOutput_Format(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Output_Format.toString());
	}

	/**
	 * Set value of Output_Format
	 * @param output_format
	 */
	public final void setOutput_Format(java.lang.String output_format)
	{
		setOutput_Format(getContext(), output_format);
	}

	/**
	 * Set value of Output_Format
	 * @param context
	 * @param output_format
	 */
	public final void setOutput_Format(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String output_format)
	{
		getMendixObject().setValue(context, MemberNames.Output_Format.toString(), output_format);
	}

	/**
	 * @return value of __ID
	 */
	public final java.lang.String get__ID()
	{
		return get__ID(getContext());
	}

	/**
	 * @param context
	 * @return value of __ID
	 */
	public final java.lang.String get__ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.__ID.toString());
	}

	/**
	 * Set value of __ID
	 * @param __id
	 */
	public final void set__ID(java.lang.String __id)
	{
		set__ID(getContext(), __id);
	}

	/**
	 * Set value of __ID
	 * @param context
	 * @param __id
	 */
	public final void set__ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String __id)
	{
		getMendixObject().setValue(context, MemberNames.__ID.toString(), __id);
	}

	/**
	 * @return value of No_Of_Request_Parameter
	 */
	public final java.lang.Integer getNo_Of_Request_Parameter()
	{
		return getNo_Of_Request_Parameter(getContext());
	}

	/**
	 * @param context
	 * @return value of No_Of_Request_Parameter
	 */
	public final java.lang.Integer getNo_Of_Request_Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_Of_Request_Parameter.toString());
	}

	/**
	 * Set value of No_Of_Request_Parameter
	 * @param no_of_request_parameter
	 */
	public final void setNo_Of_Request_Parameter(java.lang.Integer no_of_request_parameter)
	{
		setNo_Of_Request_Parameter(getContext(), no_of_request_parameter);
	}

	/**
	 * Set value of No_Of_Request_Parameter
	 * @param context
	 * @param no_of_request_parameter
	 */
	public final void setNo_Of_Request_Parameter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_request_parameter)
	{
		getMendixObject().setValue(context, MemberNames.No_Of_Request_Parameter.toString(), no_of_request_parameter);
	}

	/**
	 * @return value of Total_effort_PD
	 */
	public final java.math.BigDecimal getTotal_effort_PD()
	{
		return getTotal_effort_PD(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_effort_PD
	 */
	public final java.math.BigDecimal getTotal_effort_PD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Total_effort_PD.toString());
	}

	/**
	 * Set value of Total_effort_PD
	 * @param total_effort_pd
	 */
	public final void setTotal_effort_PD(java.math.BigDecimal total_effort_pd)
	{
		setTotal_effort_PD(getContext(), total_effort_pd);
	}

	/**
	 * Set value of Total_effort_PD
	 * @param context
	 * @param total_effort_pd
	 */
	public final void setTotal_effort_PD(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal total_effort_pd)
	{
		getMendixObject().setValue(context, MemberNames.Total_effort_PD.toString(), total_effort_pd);
	}

	/**
	 * @return value of Total_effort_PD_Rounded
	 */
	public final java.lang.Integer getTotal_effort_PD_Rounded()
	{
		return getTotal_effort_PD_Rounded(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_effort_PD_Rounded
	 */
	public final java.lang.Integer getTotal_effort_PD_Rounded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total_effort_PD_Rounded.toString());
	}

	/**
	 * Set value of Total_effort_PD_Rounded
	 * @param total_effort_pd_rounded
	 */
	public final void setTotal_effort_PD_Rounded(java.lang.Integer total_effort_pd_rounded)
	{
		setTotal_effort_PD_Rounded(getContext(), total_effort_pd_rounded);
	}

	/**
	 * Set value of Total_effort_PD_Rounded
	 * @param context
	 * @param total_effort_pd_rounded
	 */
	public final void setTotal_effort_PD_Rounded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total_effort_pd_rounded)
	{
		getMendixObject().setValue(context, MemberNames.Total_effort_PD_Rounded.toString(), total_effort_pd_rounded);
	}

	/**
	 * @return value of Orchestration_total
	 */
	public final java.lang.Integer getOrchestration_total()
	{
		return getOrchestration_total(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_total
	 */
	public final java.lang.Integer getOrchestration_total(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Orchestration_total.toString());
	}

	/**
	 * Set value of Orchestration_total
	 * @param orchestration_total
	 */
	public final void setOrchestration_total(java.lang.Integer orchestration_total)
	{
		setOrchestration_total(getContext(), orchestration_total);
	}

	/**
	 * Set value of Orchestration_total
	 * @param context
	 * @param orchestration_total
	 */
	public final void setOrchestration_total(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orchestration_total)
	{
		getMendixObject().setValue(context, MemberNames.Orchestration_total.toString(), orchestration_total);
	}

	/**
	 * @return value of TotalEffort
	 */
	public final java.math.BigDecimal getTotalEffort()
	{
		return getTotalEffort(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalEffort
	 */
	public final java.math.BigDecimal getTotalEffort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalEffort.toString());
	}

	/**
	 * Set value of TotalEffort
	 * @param totaleffort
	 */
	public final void setTotalEffort(java.math.BigDecimal totaleffort)
	{
		setTotalEffort(getContext(), totaleffort);
	}

	/**
	 * Set value of TotalEffort
	 * @param context
	 * @param totaleffort
	 */
	public final void setTotalEffort(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totaleffort)
	{
		getMendixObject().setValue(context, MemberNames.TotalEffort.toString(), totaleffort);
	}

	/**
	 * @return value of Group_Name
	 */
	public final java.lang.String getGroup_Name()
	{
		return getGroup_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Group_Name
	 */
	public final java.lang.String getGroup_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Group_Name.toString());
	}

	/**
	 * Set value of Group_Name
	 * @param group_name
	 */
	public final void setGroup_Name(java.lang.String group_name)
	{
		setGroup_Name(getContext(), group_name);
	}

	/**
	 * Set value of Group_Name
	 * @param context
	 * @param group_name
	 */
	public final void setGroup_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String group_name)
	{
		getMendixObject().setValue(context, MemberNames.Group_Name.toString(), group_name);
	}

	/**
	 * @return value of Orchestration_Service_Template
	 */
	public final myfirstmodule.proxies.Template getOrchestration_Service_Template() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Template
	 */
	public final myfirstmodule.proxies.Template getOrchestration_Service_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Template
	 * @param orchestration_service_template
	 */
	public final void setOrchestration_Service_Template(myfirstmodule.proxies.Template orchestration_service_template)
	{
		setOrchestration_Service_Template(getContext(), orchestration_service_template);
	}

	/**
	 * Set value of Orchestration_Service_Template
	 * @param context
	 * @param orchestration_service_template
	 */
	public final void setOrchestration_Service_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template orchestration_service_template)
	{
		if (orchestration_service_template == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Template.toString(), orchestration_service_template.getMendixObject().getId());
	}

	/**
	 * @return value of Orchestration_Service_Service_Attribute
	 */
	public final myfirstmodule.proxies.Service_Attribute getOrchestration_Service_Service_Attribute() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Service_Attribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Service_Attribute
	 */
	public final myfirstmodule.proxies.Service_Attribute getOrchestration_Service_Service_Attribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Service_Attribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Service_Attribute.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Service_Attribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Service_Attribute
	 * @param orchestration_service_service_attribute
	 */
	public final void setOrchestration_Service_Service_Attribute(myfirstmodule.proxies.Service_Attribute orchestration_service_service_attribute)
	{
		setOrchestration_Service_Service_Attribute(getContext(), orchestration_service_service_attribute);
	}

	/**
	 * Set value of Orchestration_Service_Service_Attribute
	 * @param context
	 * @param orchestration_service_service_attribute
	 */
	public final void setOrchestration_Service_Service_Attribute(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Service_Attribute orchestration_service_service_attribute)
	{
		if (orchestration_service_service_attribute == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Service_Attribute.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Service_Attribute.toString(), orchestration_service_service_attribute.getMendixObject().getId());
	}

	/**
	 * @return value of Orchestration_Service_Assumptions
	 */
	public final myfirstmodule.proxies.Assumptions getOrchestration_Service_Assumptions() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Assumptions(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Assumptions
	 */
	public final myfirstmodule.proxies.Assumptions getOrchestration_Service_Assumptions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Assumptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Assumptions.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Assumptions.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Assumptions
	 * @param orchestration_service_assumptions
	 */
	public final void setOrchestration_Service_Assumptions(myfirstmodule.proxies.Assumptions orchestration_service_assumptions)
	{
		setOrchestration_Service_Assumptions(getContext(), orchestration_service_assumptions);
	}

	/**
	 * Set value of Orchestration_Service_Assumptions
	 * @param context
	 * @param orchestration_service_assumptions
	 */
	public final void setOrchestration_Service_Assumptions(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Assumptions orchestration_service_assumptions)
	{
		if (orchestration_service_assumptions == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Assumptions.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Assumptions.toString(), orchestration_service_assumptions.getMendixObject().getId());
	}

	/**
	 * @return value of Orchestration_Service_Orch_SAV_dev
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_SAV_dev() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Orch_SAV_dev(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Orch_SAV_dev
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_SAV_dev(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Orch_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Orch_SAV_dev.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Orch_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Orch_SAV_dev
	 * @param orchestration_service_orch_sav_dev
	 */
	public final void setOrchestration_Service_Orch_SAV_dev(myfirstmodule.proxies.Orch_SAV orchestration_service_orch_sav_dev)
	{
		setOrchestration_Service_Orch_SAV_dev(getContext(), orchestration_service_orch_sav_dev);
	}

	/**
	 * Set value of Orchestration_Service_Orch_SAV_dev
	 * @param context
	 * @param orchestration_service_orch_sav_dev
	 */
	public final void setOrchestration_Service_Orch_SAV_dev(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Orch_SAV orchestration_service_orch_sav_dev)
	{
		if (orchestration_service_orch_sav_dev == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_SAV_dev.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_SAV_dev.toString(), orchestration_service_orch_sav_dev.getMendixObject().getId());
	}

	/**
	 * @return value of Orchestration_Service_Orch_SAV_svctype
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_SAV_svctype() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Orch_SAV_svctype(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Orch_SAV_svctype
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_SAV_svctype(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Orch_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Orch_SAV_svctype.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Orch_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Orch_SAV_svctype
	 * @param orchestration_service_orch_sav_svctype
	 */
	public final void setOrchestration_Service_Orch_SAV_svctype(myfirstmodule.proxies.Orch_SAV orchestration_service_orch_sav_svctype)
	{
		setOrchestration_Service_Orch_SAV_svctype(getContext(), orchestration_service_orch_sav_svctype);
	}

	/**
	 * Set value of Orchestration_Service_Orch_SAV_svctype
	 * @param context
	 * @param orchestration_service_orch_sav_svctype
	 */
	public final void setOrchestration_Service_Orch_SAV_svctype(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Orch_SAV orchestration_service_orch_sav_svctype)
	{
		if (orchestration_service_orch_sav_svctype == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_SAV_svctype.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_SAV_svctype.toString(), orchestration_service_orch_sav_svctype.getMendixObject().getId());
	}

	/**
	 * @return value of Orchestration_Service_Orch_output
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_output() throws com.mendix.core.CoreException
	{
		return getOrchestration_Service_Orch_output(getContext());
	}

	/**
	 * @param context
	 * @return value of Orchestration_Service_Orch_output
	 */
	public final myfirstmodule.proxies.Orch_SAV getOrchestration_Service_Orch_output(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Orch_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orchestration_Service_Orch_output.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Orch_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orchestration_Service_Orch_output
	 * @param orchestration_service_orch_output
	 */
	public final void setOrchestration_Service_Orch_output(myfirstmodule.proxies.Orch_SAV orchestration_service_orch_output)
	{
		setOrchestration_Service_Orch_output(getContext(), orchestration_service_orch_output);
	}

	/**
	 * Set value of Orchestration_Service_Orch_output
	 * @param context
	 * @param orchestration_service_orch_output
	 */
	public final void setOrchestration_Service_Orch_output(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Orch_SAV orchestration_service_orch_output)
	{
		if (orchestration_service_orch_output == null)
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_output.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orchestration_Service_Orch_output.toString(), orchestration_service_orch_output.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orchestration_ServiceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Orchestration_Service that = (myfirstmodule.proxies.Orchestration_Service) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Orchestration_Service";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
