// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Patterns_Practices
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject patterns_PracticesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Patterns_Practices";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UseCase("UseCase"),
		Service_Name("Service_Name"),
		Fault_Tolerance_Required("Fault_Tolerance_Required"),
		Service_Orchested_at("Service_Orchested_at"),
		Interact_with_Monolithic("Interact_with_Monolithic"),
		MessagePattern("MessagePattern"),
		Complexity("Complexity"),
		Complexity_In_Percentage("Complexity_In_Percentage"),
		UC("UC"),
		Template_Name("Template_Name"),
		Service_Attribute("Service_Attribute"),
		Patterns_Practices_Template("MyFirstModule.Patterns_Practices_Template"),
		Patterns_Practices_Patterns_Practices_SAV("MyFirstModule.Patterns_Practices_Patterns_Practices_SAV");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Patterns_Practices(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Patterns_Practices"));
	}

	protected Patterns_Practices(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject patterns_PracticesMendixObject)
	{
		if (patterns_PracticesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Patterns_Practices", patterns_PracticesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Patterns_Practices");

		this.patterns_PracticesMendixObject = patterns_PracticesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Patterns_Practices.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Patterns_Practices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Patterns_Practices.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Patterns_Practices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Patterns_Practices(context, mendixObject);
	}

	public static myfirstmodule.proxies.Patterns_Practices load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Patterns_Practices.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Patterns_Practices> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Patterns_Practices> result = new java.util.ArrayList<myfirstmodule.proxies.Patterns_Practices>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Patterns_Practices" + xpathConstraint))
			result.add(myfirstmodule.proxies.Patterns_Practices.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase()
	{
		return getUseCase(getContext());
	}

	/**
	 * @param context
	 * @return value of UseCase
	 */
	public final java.lang.String getUseCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseCase.toString());
	}

	/**
	 * Set value of UseCase
	 * @param usecase
	 */
	public final void setUseCase(java.lang.String usecase)
	{
		setUseCase(getContext(), usecase);
	}

	/**
	 * Set value of UseCase
	 * @param context
	 * @param usecase
	 */
	public final void setUseCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usecase)
	{
		getMendixObject().setValue(context, MemberNames.UseCase.toString(), usecase);
	}

	/**
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name()
	{
		return getService_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Name.toString());
	}

	/**
	 * Set value of Service_Name
	 * @param service_name
	 */
	public final void setService_Name(java.lang.String service_name)
	{
		setService_Name(getContext(), service_name);
	}

	/**
	 * Set value of Service_Name
	 * @param context
	 * @param service_name
	 */
	public final void setService_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_Name.toString(), service_name);
	}

	/**
	 * Set value of Fault_Tolerance_Required
	 * @param fault_tolerance_required
	 */
	public final myfirstmodule.proxies.Fault_Tolerance getFault_Tolerance_Required()
	{
		return getFault_Tolerance_Required(getContext());
	}

	/**
	 * @param context
	 * @return value of Fault_Tolerance_Required
	 */
	public final myfirstmodule.proxies.Fault_Tolerance getFault_Tolerance_Required(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Fault_Tolerance_Required.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Fault_Tolerance.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Fault_Tolerance_Required
	 * @param fault_tolerance_required
	 */
	public final void setFault_Tolerance_Required(myfirstmodule.proxies.Fault_Tolerance fault_tolerance_required)
	{
		setFault_Tolerance_Required(getContext(), fault_tolerance_required);
	}

	/**
	 * Set value of Fault_Tolerance_Required
	 * @param context
	 * @param fault_tolerance_required
	 */
	public final void setFault_Tolerance_Required(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Fault_Tolerance fault_tolerance_required)
	{
		if (fault_tolerance_required != null)
			getMendixObject().setValue(context, MemberNames.Fault_Tolerance_Required.toString(), fault_tolerance_required.toString());
		else
			getMendixObject().setValue(context, MemberNames.Fault_Tolerance_Required.toString(), null);
	}

	/**
	 * Set value of Service_Orchested_at
	 * @param service_orchested_at
	 */
	public final myfirstmodule.proxies.Service_Orchested getService_Orchested_at()
	{
		return getService_Orchested_at(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Orchested_at
	 */
	public final myfirstmodule.proxies.Service_Orchested getService_Orchested_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Service_Orchested_at.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Service_Orchested.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Service_Orchested_at
	 * @param service_orchested_at
	 */
	public final void setService_Orchested_at(myfirstmodule.proxies.Service_Orchested service_orchested_at)
	{
		setService_Orchested_at(getContext(), service_orchested_at);
	}

	/**
	 * Set value of Service_Orchested_at
	 * @param context
	 * @param service_orchested_at
	 */
	public final void setService_Orchested_at(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Service_Orchested service_orchested_at)
	{
		if (service_orchested_at != null)
			getMendixObject().setValue(context, MemberNames.Service_Orchested_at.toString(), service_orchested_at.toString());
		else
			getMendixObject().setValue(context, MemberNames.Service_Orchested_at.toString(), null);
	}

	/**
	 * Set value of Interact_with_Monolithic
	 * @param interact_with_monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getInteract_with_Monolithic()
	{
		return getInteract_with_Monolithic(getContext());
	}

	/**
	 * @param context
	 * @return value of Interact_with_Monolithic
	 */
	public final myfirstmodule.proxies.Yes_No getInteract_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Interact_with_Monolithic.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Yes_No.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Interact_with_Monolithic
	 * @param interact_with_monolithic
	 */
	public final void setInteract_with_Monolithic(myfirstmodule.proxies.Yes_No interact_with_monolithic)
	{
		setInteract_with_Monolithic(getContext(), interact_with_monolithic);
	}

	/**
	 * Set value of Interact_with_Monolithic
	 * @param context
	 * @param interact_with_monolithic
	 */
	public final void setInteract_with_Monolithic(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Yes_No interact_with_monolithic)
	{
		if (interact_with_monolithic != null)
			getMendixObject().setValue(context, MemberNames.Interact_with_Monolithic.toString(), interact_with_monolithic.toString());
		else
			getMendixObject().setValue(context, MemberNames.Interact_with_Monolithic.toString(), null);
	}

	/**
	 * Set value of MessagePattern
	 * @param messagepattern
	 */
	public final myfirstmodule.proxies.Message_pattern getMessagePattern()
	{
		return getMessagePattern(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagePattern
	 */
	public final myfirstmodule.proxies.Message_pattern getMessagePattern(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessagePattern.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Message_pattern.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessagePattern
	 * @param messagepattern
	 */
	public final void setMessagePattern(myfirstmodule.proxies.Message_pattern messagepattern)
	{
		setMessagePattern(getContext(), messagepattern);
	}

	/**
	 * Set value of MessagePattern
	 * @param context
	 * @param messagepattern
	 */
	public final void setMessagePattern(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Message_pattern messagepattern)
	{
		if (messagepattern != null)
			getMendixObject().setValue(context, MemberNames.MessagePattern.toString(), messagepattern.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessagePattern.toString(), null);
	}

	/**
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity()
	{
		return getComplexity(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity
	 */
	public final java.math.BigDecimal getComplexity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity.toString());
	}

	/**
	 * Set value of Complexity
	 * @param complexity
	 */
	public final void setComplexity(java.math.BigDecimal complexity)
	{
		setComplexity(getContext(), complexity);
	}

	/**
	 * Set value of Complexity
	 * @param context
	 * @param complexity
	 */
	public final void setComplexity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity)
	{
		getMendixObject().setValue(context, MemberNames.Complexity.toString(), complexity);
	}

	/**
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage()
	{
		return getComplexity_In_Percentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Complexity_In_Percentage
	 */
	public final java.math.BigDecimal getComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Complexity_In_Percentage.toString());
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(java.math.BigDecimal complexity_in_percentage)
	{
		setComplexity_In_Percentage(getContext(), complexity_in_percentage);
	}

	/**
	 * Set value of Complexity_In_Percentage
	 * @param context
	 * @param complexity_in_percentage
	 */
	public final void setComplexity_In_Percentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal complexity_in_percentage)
	{
		getMendixObject().setValue(context, MemberNames.Complexity_In_Percentage.toString(), complexity_in_percentage);
	}

	/**
	 * @return value of UC
	 */
	public final java.lang.Long getUC()
	{
		return getUC(getContext());
	}

	/**
	 * @param context
	 * @return value of UC
	 */
	public final java.lang.Long getUC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UC.toString());
	}

	/**
	 * Set value of UC
	 * @param uc
	 */
	public final void setUC(java.lang.Long uc)
	{
		setUC(getContext(), uc);
	}

	/**
	 * Set value of UC
	 * @param context
	 * @param uc
	 */
	public final void setUC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long uc)
	{
		getMendixObject().setValue(context, MemberNames.UC.toString(), uc);
	}

	/**
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name()
	{
		return getTemplate_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Name
	 */
	public final java.lang.String getTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Name.toString());
	}

	/**
	 * Set value of Template_Name
	 * @param template_name
	 */
	public final void setTemplate_Name(java.lang.String template_name)
	{
		setTemplate_Name(getContext(), template_name);
	}

	/**
	 * Set value of Template_Name
	 * @param context
	 * @param template_name
	 */
	public final void setTemplate_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_name)
	{
		getMendixObject().setValue(context, MemberNames.Template_Name.toString(), template_name);
	}

	/**
	 * @return value of Service_Attribute
	 */
	public final java.lang.String getService_Attribute()
	{
		return getService_Attribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Attribute
	 */
	public final java.lang.String getService_Attribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Attribute.toString());
	}

	/**
	 * Set value of Service_Attribute
	 * @param service_attribute
	 */
	public final void setService_Attribute(java.lang.String service_attribute)
	{
		setService_Attribute(getContext(), service_attribute);
	}

	/**
	 * Set value of Service_Attribute
	 * @param context
	 * @param service_attribute
	 */
	public final void setService_Attribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_attribute)
	{
		getMendixObject().setValue(context, MemberNames.Service_Attribute.toString(), service_attribute);
	}

	/**
	 * @return value of Patterns_Practices_Template
	 */
	public final myfirstmodule.proxies.Template getPatterns_Practices_Template() throws com.mendix.core.CoreException
	{
		return getPatterns_Practices_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Patterns_Practices_Template
	 */
	public final myfirstmodule.proxies.Template getPatterns_Practices_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Patterns_Practices_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Patterns_Practices_Template
	 * @param patterns_practices_template
	 */
	public final void setPatterns_Practices_Template(myfirstmodule.proxies.Template patterns_practices_template)
	{
		setPatterns_Practices_Template(getContext(), patterns_practices_template);
	}

	/**
	 * Set value of Patterns_Practices_Template
	 * @param context
	 * @param patterns_practices_template
	 */
	public final void setPatterns_Practices_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template patterns_practices_template)
	{
		if (patterns_practices_template == null)
			getMendixObject().setValue(context, MemberNames.Patterns_Practices_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Patterns_Practices_Template.toString(), patterns_practices_template.getMendixObject().getId());
	}

	/**
	 * @return value of Patterns_Practices_Patterns_Practices_SAV
	 */
	public final myfirstmodule.proxies.Patterns_Practices_SAV getPatterns_Practices_Patterns_Practices_SAV() throws com.mendix.core.CoreException
	{
		return getPatterns_Practices_Patterns_Practices_SAV(getContext());
	}

	/**
	 * @param context
	 * @return value of Patterns_Practices_Patterns_Practices_SAV
	 */
	public final myfirstmodule.proxies.Patterns_Practices_SAV getPatterns_Practices_Patterns_Practices_SAV(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Patterns_Practices_SAV result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Patterns_Practices_Patterns_Practices_SAV.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Patterns_Practices_SAV.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Patterns_Practices_Patterns_Practices_SAV
	 * @param patterns_practices_patterns_practices_sav
	 */
	public final void setPatterns_Practices_Patterns_Practices_SAV(myfirstmodule.proxies.Patterns_Practices_SAV patterns_practices_patterns_practices_sav)
	{
		setPatterns_Practices_Patterns_Practices_SAV(getContext(), patterns_practices_patterns_practices_sav);
	}

	/**
	 * Set value of Patterns_Practices_Patterns_Practices_SAV
	 * @param context
	 * @param patterns_practices_patterns_practices_sav
	 */
	public final void setPatterns_Practices_Patterns_Practices_SAV(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Patterns_Practices_SAV patterns_practices_patterns_practices_sav)
	{
		if (patterns_practices_patterns_practices_sav == null)
			getMendixObject().setValue(context, MemberNames.Patterns_Practices_Patterns_Practices_SAV.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Patterns_Practices_Patterns_Practices_SAV.toString(), patterns_practices_patterns_practices_sav.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return patterns_PracticesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Patterns_Practices that = (myfirstmodule.proxies.Patterns_Practices) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Patterns_Practices";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
