// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Performance
{
	_200ms(new java.lang.String[][] { new java.lang.String[] { "en_US", "< 200ms" } }),
	__1sec(new java.lang.String[][] { new java.lang.String[] { "en_US", "< 1sec" } }),
	_2secs(new java.lang.String[][] { new java.lang.String[] { "en_US", "< 2secs" } }),
	_3_secs(new java.lang.String[][] { new java.lang.String[] { "en_US", "<3 secs" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Performance(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
