// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Photo extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Photo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PicId("PicId"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Photo_Template("MyFirstModule.Photo_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Photo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Photo"));
	}

	protected Photo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject photoMendixObject)
	{
		super(context, photoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Photo", photoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Photo");
	}

	/**
	 * @deprecated Use 'Photo.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Photo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Photo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Photo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Photo(context, mendixObject);
	}

	public static myfirstmodule.proxies.Photo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Photo.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Photo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Photo> result = new java.util.ArrayList<myfirstmodule.proxies.Photo>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Photo" + xpathConstraint))
			result.add(myfirstmodule.proxies.Photo.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of PicId
	 */
	public final java.lang.String getPicId()
	{
		return getPicId(getContext());
	}

	/**
	 * @param context
	 * @return value of PicId
	 */
	public final java.lang.String getPicId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PicId.toString());
	}

	/**
	 * Set value of PicId
	 * @param picid
	 */
	public final void setPicId(java.lang.String picid)
	{
		setPicId(getContext(), picid);
	}

	/**
	 * Set value of PicId
	 * @param context
	 * @param picid
	 */
	public final void setPicId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String picid)
	{
		getMendixObject().setValue(context, MemberNames.PicId.toString(), picid);
	}

	/**
	 * @return value of Photo_Template
	 */
	public final java.util.List<myfirstmodule.proxies.Template> getPhoto_Template() throws com.mendix.core.CoreException
	{
		return getPhoto_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Photo_Template
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.Template> getPhoto_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Template> result = new java.util.ArrayList<myfirstmodule.proxies.Template>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Photo_Template.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.Template.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Photo_Template
	 * @param photo_template
	 */
	public final void setPhoto_Template(java.util.List<myfirstmodule.proxies.Template> photo_template)
	{
		setPhoto_Template(getContext(), photo_template);
	}

	/**
	 * Set value of Photo_Template
	 * @param context
	 * @param photo_template
	 */
	public final void setPhoto_Template(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.Template> photo_template)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.Template proxyObject : photo_template)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Photo_Template.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Photo that = (myfirstmodule.proxies.Photo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Photo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
