// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Service_Attribute_Entries
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject service_Attribute_EntriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Service_Attribute_Entries";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value_Id("Value_Id"),
		Value_Point("Value_Point"),
		Value_Name("Value_Name"),
		Service_Name("Service_Name"),
		Service_Attribute("Service_Attribute");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Service_Attribute_Entries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Service_Attribute_Entries"));
	}

	protected Service_Attribute_Entries(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject service_Attribute_EntriesMendixObject)
	{
		if (service_Attribute_EntriesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Service_Attribute_Entries", service_Attribute_EntriesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Service_Attribute_Entries");

		this.service_Attribute_EntriesMendixObject = service_Attribute_EntriesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Service_Attribute_Entries.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Service_Attribute_Entries initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Service_Attribute_Entries.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Service_Attribute_Entries initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Service_Attribute_Entries(context, mendixObject);
	}

	public static myfirstmodule.proxies.Service_Attribute_Entries load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Service_Attribute_Entries.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Service_Attribute_Entries> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Service_Attribute_Entries> result = new java.util.ArrayList<myfirstmodule.proxies.Service_Attribute_Entries>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Service_Attribute_Entries" + xpathConstraint))
			result.add(myfirstmodule.proxies.Service_Attribute_Entries.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value_Id
	 */
	public final java.lang.Long getValue_Id()
	{
		return getValue_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Id
	 */
	public final java.lang.Long getValue_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Value_Id.toString());
	}

	/**
	 * Set value of Value_Id
	 * @param value_id
	 */
	public final void setValue_Id(java.lang.Long value_id)
	{
		setValue_Id(getContext(), value_id);
	}

	/**
	 * Set value of Value_Id
	 * @param context
	 * @param value_id
	 */
	public final void setValue_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long value_id)
	{
		getMendixObject().setValue(context, MemberNames.Value_Id.toString(), value_id);
	}

	/**
	 * @return value of Value_Point
	 */
	public final java.lang.Double getValue_Point()
	{
		return getValue_Point(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Point
	 */
	public final java.lang.Double getValue_Point(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Value_Point.toString());
	}

	/**
	 * Set value of Value_Point
	 * @param value_point
	 */
	public final void setValue_Point(java.lang.Double value_point)
	{
		setValue_Point(getContext(), value_point);
	}

	/**
	 * Set value of Value_Point
	 * @param context
	 * @param value_point
	 */
	public final void setValue_Point(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double value_point)
	{
		getMendixObject().setValue(context, MemberNames.Value_Point.toString(), value_point);
	}

	/**
	 * @return value of Value_Name
	 */
	public final java.lang.String getValue_Name()
	{
		return getValue_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Name
	 */
	public final java.lang.String getValue_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value_Name.toString());
	}

	/**
	 * Set value of Value_Name
	 * @param value_name
	 */
	public final void setValue_Name(java.lang.String value_name)
	{
		setValue_Name(getContext(), value_name);
	}

	/**
	 * Set value of Value_Name
	 * @param context
	 * @param value_name
	 */
	public final void setValue_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value_name)
	{
		getMendixObject().setValue(context, MemberNames.Value_Name.toString(), value_name);
	}

	/**
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name()
	{
		return getService_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Name.toString());
	}

	/**
	 * Set value of Service_Name
	 * @param service_name
	 */
	public final void setService_Name(java.lang.String service_name)
	{
		setService_Name(getContext(), service_name);
	}

	/**
	 * Set value of Service_Name
	 * @param context
	 * @param service_name
	 */
	public final void setService_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_Name.toString(), service_name);
	}

	/**
	 * @return value of Service_Attribute
	 */
	public final java.lang.String getService_Attribute()
	{
		return getService_Attribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Attribute
	 */
	public final java.lang.String getService_Attribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Attribute.toString());
	}

	/**
	 * Set value of Service_Attribute
	 * @param service_attribute
	 */
	public final void setService_Attribute(java.lang.String service_attribute)
	{
		setService_Attribute(getContext(), service_attribute);
	}

	/**
	 * Set value of Service_Attribute
	 * @param context
	 * @param service_attribute
	 */
	public final void setService_Attribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_attribute)
	{
		getMendixObject().setValue(context, MemberNames.Service_Attribute.toString(), service_attribute);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return service_Attribute_EntriesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Service_Attribute_Entries that = (myfirstmodule.proxies.Service_Attribute_Entries) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Service_Attribute_Entries";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
