// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Service_Attribute_Local
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject service_Attribute_LocalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Service_Attribute_Local";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Service_id("Service_id"),
		Service_Name("Service_Name"),
		Service_Point("Service_Point"),
		Service_Attribute_Name("Service_Attribute_Name"),
		Service_Attribute_Local_Template("MyFirstModule.Service_Attribute_Local_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Service_Attribute_Local(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Service_Attribute_Local"));
	}

	protected Service_Attribute_Local(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject service_Attribute_LocalMendixObject)
	{
		if (service_Attribute_LocalMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Service_Attribute_Local", service_Attribute_LocalMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Service_Attribute_Local");

		this.service_Attribute_LocalMendixObject = service_Attribute_LocalMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Service_Attribute_Local.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Service_Attribute_Local initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Service_Attribute_Local.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Service_Attribute_Local initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Service_Attribute_Local(context, mendixObject);
	}

	public static myfirstmodule.proxies.Service_Attribute_Local load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Service_Attribute_Local.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Service_Attribute_Local> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Service_Attribute_Local> result = new java.util.ArrayList<myfirstmodule.proxies.Service_Attribute_Local>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Service_Attribute_Local" + xpathConstraint))
			result.add(myfirstmodule.proxies.Service_Attribute_Local.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Service_id
	 */
	public final java.lang.Long getService_id()
	{
		return getService_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_id
	 */
	public final java.lang.Long getService_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Service_id.toString());
	}

	/**
	 * Set value of Service_id
	 * @param service_id
	 */
	public final void setService_id(java.lang.Long service_id)
	{
		setService_id(getContext(), service_id);
	}

	/**
	 * Set value of Service_id
	 * @param context
	 * @param service_id
	 */
	public final void setService_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long service_id)
	{
		getMendixObject().setValue(context, MemberNames.Service_id.toString(), service_id);
	}

	/**
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name()
	{
		return getService_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Name
	 */
	public final java.lang.String getService_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Name.toString());
	}

	/**
	 * Set value of Service_Name
	 * @param service_name
	 */
	public final void setService_Name(java.lang.String service_name)
	{
		setService_Name(getContext(), service_name);
	}

	/**
	 * Set value of Service_Name
	 * @param context
	 * @param service_name
	 */
	public final void setService_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_Name.toString(), service_name);
	}

	/**
	 * @return value of Service_Point
	 */
	public final java.lang.Integer getService_Point()
	{
		return getService_Point(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Point
	 */
	public final java.lang.Integer getService_Point(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Service_Point.toString());
	}

	/**
	 * Set value of Service_Point
	 * @param service_point
	 */
	public final void setService_Point(java.lang.Integer service_point)
	{
		setService_Point(getContext(), service_point);
	}

	/**
	 * Set value of Service_Point
	 * @param context
	 * @param service_point
	 */
	public final void setService_Point(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer service_point)
	{
		getMendixObject().setValue(context, MemberNames.Service_Point.toString(), service_point);
	}

	/**
	 * @return value of Service_Attribute_Name
	 */
	public final java.lang.String getService_Attribute_Name()
	{
		return getService_Attribute_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Attribute_Name
	 */
	public final java.lang.String getService_Attribute_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service_Attribute_Name.toString());
	}

	/**
	 * Set value of Service_Attribute_Name
	 * @param service_attribute_name
	 */
	public final void setService_Attribute_Name(java.lang.String service_attribute_name)
	{
		setService_Attribute_Name(getContext(), service_attribute_name);
	}

	/**
	 * Set value of Service_Attribute_Name
	 * @param context
	 * @param service_attribute_name
	 */
	public final void setService_Attribute_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service_attribute_name)
	{
		getMendixObject().setValue(context, MemberNames.Service_Attribute_Name.toString(), service_attribute_name);
	}

	/**
	 * @return value of Service_Attribute_Local_Template
	 */
	public final myfirstmodule.proxies.Template getService_Attribute_Local_Template() throws com.mendix.core.CoreException
	{
		return getService_Attribute_Local_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Attribute_Local_Template
	 */
	public final myfirstmodule.proxies.Template getService_Attribute_Local_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Service_Attribute_Local_Template.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Service_Attribute_Local_Template
	 * @param service_attribute_local_template
	 */
	public final void setService_Attribute_Local_Template(myfirstmodule.proxies.Template service_attribute_local_template)
	{
		setService_Attribute_Local_Template(getContext(), service_attribute_local_template);
	}

	/**
	 * Set value of Service_Attribute_Local_Template
	 * @param context
	 * @param service_attribute_local_template
	 */
	public final void setService_Attribute_Local_Template(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Template service_attribute_local_template)
	{
		if (service_attribute_local_template == null)
			getMendixObject().setValue(context, MemberNames.Service_Attribute_Local_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Service_Attribute_Local_Template.toString(), service_attribute_local_template.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return service_Attribute_LocalMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Service_Attribute_Local that = (myfirstmodule.proxies.Service_Attribute_Local) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Service_Attribute_Local";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
