// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Template
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject templateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Template";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TemplateName("TemplateName"),
		Created_On("Created_On"),
		Description("Description"),
		Total_PD("Total_PD"),
		Template_Icon("Template_Icon"),
		Template_Title("Template_Title"),
		Total_PD_QA("Total_PD_QA"),
		Template_Copy("Template_Copy"),
		Template_Archieve("Template_Archieve"),
		Template_Status("Template_Status"),
		Template_Report("MyFirstModule.Template_Report");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Template(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Template"));
	}

	protected Template(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject templateMendixObject)
	{
		if (templateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Template", templateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Template");

		this.templateMendixObject = templateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Template.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Template.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Template initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Template(context, mendixObject);
	}

	public static myfirstmodule.proxies.Template load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Template.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Template> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Template> result = new java.util.ArrayList<myfirstmodule.proxies.Template>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Template" + xpathConstraint))
			result.add(myfirstmodule.proxies.Template.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TemplateName
	 */
	public final java.lang.String getTemplateName()
	{
		return getTemplateName(getContext());
	}

	/**
	 * @param context
	 * @return value of TemplateName
	 */
	public final java.lang.String getTemplateName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TemplateName.toString());
	}

	/**
	 * Set value of TemplateName
	 * @param templatename
	 */
	public final void setTemplateName(java.lang.String templatename)
	{
		setTemplateName(getContext(), templatename);
	}

	/**
	 * Set value of TemplateName
	 * @param context
	 * @param templatename
	 */
	public final void setTemplateName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String templatename)
	{
		getMendixObject().setValue(context, MemberNames.TemplateName.toString(), templatename);
	}

	/**
	 * @return value of Created_On
	 */
	public final java.lang.String getCreated_On()
	{
		return getCreated_On(getContext());
	}

	/**
	 * @param context
	 * @return value of Created_On
	 */
	public final java.lang.String getCreated_On(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Created_On.toString());
	}

	/**
	 * Set value of Created_On
	 * @param created_on
	 */
	public final void setCreated_On(java.lang.String created_on)
	{
		setCreated_On(getContext(), created_on);
	}

	/**
	 * Set value of Created_On
	 * @param context
	 * @param created_on
	 */
	public final void setCreated_On(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String created_on)
	{
		getMendixObject().setValue(context, MemberNames.Created_On.toString(), created_on);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Total_PD
	 */
	public final java.math.BigDecimal getTotal_PD()
	{
		return getTotal_PD(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_PD
	 */
	public final java.math.BigDecimal getTotal_PD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Total_PD.toString());
	}

	/**
	 * Set value of Total_PD
	 * @param total_pd
	 */
	public final void setTotal_PD(java.math.BigDecimal total_pd)
	{
		setTotal_PD(getContext(), total_pd);
	}

	/**
	 * Set value of Total_PD
	 * @param context
	 * @param total_pd
	 */
	public final void setTotal_PD(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal total_pd)
	{
		getMendixObject().setValue(context, MemberNames.Total_PD.toString(), total_pd);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getTemplate_Icon(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Template_Icon.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setTemplate_Icon(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Template_Icon.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return value of Template_Title
	 */
	public final java.lang.String getTemplate_Title()
	{
		return getTemplate_Title(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Title
	 */
	public final java.lang.String getTemplate_Title(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Title.toString());
	}

	/**
	 * Set value of Template_Title
	 * @param template_title
	 */
	public final void setTemplate_Title(java.lang.String template_title)
	{
		setTemplate_Title(getContext(), template_title);
	}

	/**
	 * Set value of Template_Title
	 * @param context
	 * @param template_title
	 */
	public final void setTemplate_Title(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_title)
	{
		getMendixObject().setValue(context, MemberNames.Template_Title.toString(), template_title);
	}

	/**
	 * @return value of Total_PD_QA
	 */
	public final java.math.BigDecimal getTotal_PD_QA()
	{
		return getTotal_PD_QA(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_PD_QA
	 */
	public final java.math.BigDecimal getTotal_PD_QA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Total_PD_QA.toString());
	}

	/**
	 * Set value of Total_PD_QA
	 * @param total_pd_qa
	 */
	public final void setTotal_PD_QA(java.math.BigDecimal total_pd_qa)
	{
		setTotal_PD_QA(getContext(), total_pd_qa);
	}

	/**
	 * Set value of Total_PD_QA
	 * @param context
	 * @param total_pd_qa
	 */
	public final void setTotal_PD_QA(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal total_pd_qa)
	{
		getMendixObject().setValue(context, MemberNames.Total_PD_QA.toString(), total_pd_qa);
	}

	/**
	 * @return value of Template_Copy
	 */
	public final java.lang.String getTemplate_Copy()
	{
		return getTemplate_Copy(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Copy
	 */
	public final java.lang.String getTemplate_Copy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Template_Copy.toString());
	}

	/**
	 * Set value of Template_Copy
	 * @param template_copy
	 */
	public final void setTemplate_Copy(java.lang.String template_copy)
	{
		setTemplate_Copy(getContext(), template_copy);
	}

	/**
	 * Set value of Template_Copy
	 * @param context
	 * @param template_copy
	 */
	public final void setTemplate_Copy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String template_copy)
	{
		getMendixObject().setValue(context, MemberNames.Template_Copy.toString(), template_copy);
	}

	/**
	 * @return value of Template_Archieve
	 */
	public final java.lang.Boolean getTemplate_Archieve()
	{
		return getTemplate_Archieve(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Archieve
	 */
	public final java.lang.Boolean getTemplate_Archieve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Template_Archieve.toString());
	}

	/**
	 * Set value of Template_Archieve
	 * @param template_archieve
	 */
	public final void setTemplate_Archieve(java.lang.Boolean template_archieve)
	{
		setTemplate_Archieve(getContext(), template_archieve);
	}

	/**
	 * Set value of Template_Archieve
	 * @param context
	 * @param template_archieve
	 */
	public final void setTemplate_Archieve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean template_archieve)
	{
		getMendixObject().setValue(context, MemberNames.Template_Archieve.toString(), template_archieve);
	}

	/**
	 * Set value of Template_Status
	 * @param template_status
	 */
	public final myfirstmodule.proxies.TemplateStatus getTemplate_Status()
	{
		return getTemplate_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Status
	 */
	public final myfirstmodule.proxies.TemplateStatus getTemplate_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Template_Status.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.TemplateStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Template_Status
	 * @param template_status
	 */
	public final void setTemplate_Status(myfirstmodule.proxies.TemplateStatus template_status)
	{
		setTemplate_Status(getContext(), template_status);
	}

	/**
	 * Set value of Template_Status
	 * @param context
	 * @param template_status
	 */
	public final void setTemplate_Status(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TemplateStatus template_status)
	{
		if (template_status != null)
			getMendixObject().setValue(context, MemberNames.Template_Status.toString(), template_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Template_Status.toString(), null);
	}

	/**
	 * @return value of Template_Report
	 */
	public final myfirstmodule.proxies.Report getTemplate_Report() throws com.mendix.core.CoreException
	{
		return getTemplate_Report(getContext());
	}

	/**
	 * @param context
	 * @return value of Template_Report
	 */
	public final myfirstmodule.proxies.Report getTemplate_Report(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Report result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Template_Report.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Report.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Template_Report
	 * @param template_report
	 */
	public final void setTemplate_Report(myfirstmodule.proxies.Report template_report)
	{
		setTemplate_Report(getContext(), template_report);
	}

	/**
	 * Set value of Template_Report
	 * @param context
	 * @param template_report
	 */
	public final void setTemplate_Report(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Report template_report)
	{
		if (template_report == null)
			getMendixObject().setValue(context, MemberNames.Template_Report.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Template_Report.toString(), template_report.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return templateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Template that = (myfirstmodule.proxies.Template) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Template";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
